### ISSUE TITLE
Manual resize option

### ISSUE THREAD

**Issue by mamandell** [plusonelabs/calendar-widget#100]
Widget refuses to be resizable on Galaxy SII.  It would be great if there was some kind of "advanced" option to manually set the size.  Alternatively, an option so that it would size itself as full pane by default.

**Comment by yafp** [comment]
I guess this issue is heavily outdated.
Apart from that i haven't had any issues with resizing the widget over years on multiple devices.

@allanlaal  & @mamandell:
Is that issue still valid for you?

**Comment by mpost** [comment]
I agree with @yafp. Closing the issue for now.

**Comment by mamandell** [comment]
No longer needed for me.   Thanks for being open source! I resized it for my phone by recompiling with the minimum size set larger   I still use this.  .Great app!
