### ISSUE TITLE
Don't limit location to 1 line

### ISSUE THREAD

**Issue by erenoglu** [plusonelabs/calendar-widget#106]
I have many meetings on conference calls and people generally write very long sentences before they actually write the bridge code.

With current implementation I can't see those bridge codes without first opening the calendar app. 

So if we had an option to not limit the location field to one line and let it wrap to multiple lines then I could see my audio bridges without needing to open the calendar app first.

**Comment by yvolk** [comment]
In "All in one row" Event entry layout, when "Multiline title" is set then the location is not limited to one line.

**Comment by yvolk** [comment]
I think that for uniformity Location should be shown in multiple lines, if "Multiline  title" setting turned on?!
In ant layout...

**Comment by yvolk** [comment]
I added "Multiline details" option to the Layout section.

Implemented in v.3.1.0, please check here: #320
