### ISSUE TITLE
Location field font selection 

### ISSUE THREAD

**Issue by erenoglu** [plusonelabs/calendar-widget#107]
Location field is very important for me as I use it to dial to my meetings. The dialing bridge code is stated there. 
Now it is shown in small font and in a faded color.  It is very tough to read easily. 

The would be good if we could choose the font size and color.

**Comment by yvolk** [comment]
@erenoglu  Since v.3.0 we can directly set color ("Text shading") of the Location field + text size for the whole widget can be changed.
Moreover, since v.3.1 we have multiline Location in the default two lines layout, allowing to see the whole Location text.
So I think that we did this.
