### ISSUE TITLE
Multi-day all day events should continue to be visible when "Fill all day events" is off.

### ISSUE THREAD

**Issue by HHest** [plusonelabs/calendar-widget#111]
I don't particularly like the "Fill all day events" feature, as it puts an entry for each day of an all day event.  I prefer seeing only one entry.  However, in this mode, when the 1st day is past, no entry appears for the remaining days.

As long as the event is going on, it would be better if an entry remains for "Today".  For example, let's say I have an all day event that covers Saturday, Sunday & Monday.  On Sunday & Monday, there should be an entry in "Today" with the remark "-> Monday..."

**Comment by yvolk** [comment]
As I see now, when "Fill all days events" is turned off, we do have today's entry for that event.
