### ISSUE TITLE
All-day events for current day disappear in the evening

### ISSUE THREAD

**Issue by geckocavemen** [plusonelabs/calendar-widget#116]
At about 8:30 pm I noticed that two all-day events for today have disappeared from the widget.  They were there earlier and are still in my calendar so I can only assume that after a certain time in the evening the widget will no longer display all-day events for the current day.  It should display current all-day events until 11:59 pm.

**Comment by maiser2011** [comment]
Birthdays that should show until 11:59pm disappear around 8:00pm. The birthdays are from the Google Contact's Birthdays. The time zone is US Central Time.

**Comment by yvolk** [comment]
@maiser2011 "Events that ended recently" option that is implemented in upcoming v.1.9, will allow you to see such events.

**Comment by maiser2011** [comment]
Will version 1.9 be released soon?
