### ISSUE TITLE
Manual instant sync

### ISSUE THREAD

**Issue by endrepalinkas** [plusonelabs/calendar-widget#120]
Oftentimes I update the calendar (either by adding an event on the phone, or syncing with Exchange), then I worry about the new event not appearing in the widget. It's there in the calendar, but not in the widget UI yet.

Usually the widget gets the updates in a minute or so. But right now for example, I added an event which is over 1 month in advance, and it's still not there, after waiting about 10 minutes.

Would it be possible to add an (optional) sync button to the widget header, to instantly update the widget events from the calendars? 

It would be the icing on the cake if you could configure this sync button to also sync the phone calendar with the connected online accounts before syncing the widget UI!

**Comment by chunte** [comment]
I do face this little nagging issue. It does take a while for the widget to update, seems random to me...

**Comment by yvolk** [comment]
My experience shows that the delay in the "natural update" of the event list is caused by underlying Calendar application itself. Recently I noticed the same problem inside Google Calendar: looking in its own Agenda screen, I changed one event but didn't see any changes in the Agenda until I returned to the Home screen and reopened the Calendar.

I think a dedicated "Refresh" button will really help in such cases. Maybe in order to conserve space we better create another "Widget button" for the Calendar-widget?! Pressing on that separate small widget will refresh main (Agenda) widget?!

**Comment by foszor** [comment]
I came here to request this feature for the exact same reasons. Please add a refresh button.

**Comment by yvolk** [comment]
@foszor Do you mean another button on a Widget's header? 
Or (and?) a separate "Refresh calendar" widget?

**Comment by foszor** [comment]
@yvolk on the header would be perfect. Next to the "+" for adding events.

**Comment by endrepalinkas** [comment]
I agree with @foszor , next to the "+" would be great

**Comment by yvolk** [comment]
I added refresh button to a Widget header, using icons from Android icon pack. I have to remove opacity from them though to look as existing icons on the header.
![refreshbutton](https://cloud.githubusercontent.com/assets/207716/6996457/607feb3a-db92-11e4-915c-1ba14bca8ced.png)

**Comment by endrepalinkas** [comment]
Thank you!

**Comment by o0oke** [comment]
it would be better to enable the widget can refresh by itself every n(enable setting by user) hours.
or adding the drop down to refresh the list. 
I checked sometime the drop down the refresh on the task list will works but sometime do not.

**Comment by hmac01** [comment]
On my Samsung Galaxy S7, the refresh button doesn't work when I tap the symbol on the header of the widget.

**Comment by frequentdrop** [comment]
Same here on a p9000. No refresh on buttonevent. apperently no errors in catlog.
