### ISSUE TITLE
Task & Notes App integration 

### ISSUE THREAD

**Issue by mjt543** [plusonelabs/calendar-widget#121]
I have discovered that Tasks & Notes is no longer integrating with Calendar Widget. I cannot determine from which end the interruption originates, but I have brought the issue to the attention of the Tasks & Notes app as well.

Thanks,
Michael

**Comment by yvolk** [comment]
Since v.2.1. our widget supports tasks and intergates with a couple of task apps, see #308 
Due and incomplete tasks are shown, naturally.

**Comment by yvolk** [comment]
Looks like the "Tasks & Notes" app bug (or their deliberate decision...)
