### ISSUE TITLE
show events that ended in past X hours (configurable)

### ISSUE THREAD

**Issue by rosenbergj** [plusonelabs/calendar-widget#122]
I generally want to be able to see recently-ended events, but in this widget, they disappear as soon as the ending time is reached. I'd like to be able to configure the widget such that events don't disappear until X hours after they've ended. (Another widget lets you show events until midnight of the day they take place, which would also work for me; my events tend not to end immediately at midnight.)

**Comment by allanlaal** [comment]
past events could also be greyed out or be more opaque

**Comment by yvolk** [comment]
@allanlaal We recently added "Past events background color" option (to be released yet)

**Comment by yvolk** [comment]
@rosenbergj @mpost @allanlaal For consistency and simplicity I think we better have a list of predefined values. What exactly values may be needed? 

So the name of the new option,  located in "Event filters - Past events" will be: "Show events that ended some time ago"
I would start from these values:
1. "(this option is turned off)" - just like for another option: "Show past events with color"
2. "1 hour ago"
3. "2 hours ago"
4. "Anytime today"
5. "24 hours ago"
...
?

**Comment by yvolk** [comment]
Implemented. Now "Event Filters" preferences screen looks like this:
![scr-event-filters](https://cloud.githubusercontent.com/assets/207716/7215054/f0a0cfaa-e5cd-11e4-8717-3c3ba734c471.png)

**Comment by mpost** [comment]
I like this feature. One suggestion regarding the wording. I would remove the part ". Or turn this option off".

**Comment by lexa1** [comment]
please extend the option to show past events with "one week ago"
