### ISSUE TITLE
Highlighting the current day

### ISSUE THREAD

**Issue by asturnauta** [plusonelabs/calendar-widget#124]
It would be great to can configure a diferent colour for 'today events' and difference them to the future events.
For example i would like to configure today events in red colour to easily see today events.

**Comment by maiser2011** [comment]
Current day events could have option to be shown in bold or italic font to distinguish from other day/s events.

**Comment by yvolk** [comment]
As one of users suggested, we could add background color setting for Today's events...

**Comment by mdromed** [comment]
please let us change background color or font color for today events.
Regards

**Comment by yvolk** [comment]
I'm adding this in the upcoming v. 2.2
![Screenshot_20190829-210251](https://user-images.githubusercontent.com/207716/63965019-fecdf780-caa0-11e9-892e-6487b5de93dd.png)

**Comment by bushrang3r** [comment]
This is a good idea, but in reference to #315 , it doesn't solve the visibility of days that aren't today.
In the screenshot above, 'Sunday's task' occupies the same space as MONDAY, AUGUST 19.

**Comment by yvolk** [comment]
@bushrang3r I understand this :-)

**Comment by yvolk** [comment]
Released in Beta version 3.0, please try: https://play.google.com/apps/testing/org.andstatus.todoagenda
Note: Due to lots of internal changes existing widgets should be recreated. Sorry for inconvenience.
