### ISSUE TITLE
Add Touchdown calendar support

### ISSUE THREAD

**Issue by DasExperimentator** [plusonelabs/calendar-widget#135]
It would be great if the Calendar Widget could display calendar appointments from Touchdown (an app for MS Exchange synchronization). At the moment there are only a few widgets that are able to access Touchdown calendar:
- Agenda Widget - at the time of opening this ticket, the Agenda Widget is not updated for quite some months and does not work in Android 4.4.
- Pure Calendar Widget - this one is not as nice and convenient as the Calendar Widget

In my opinion, adding Touchdown support would greatly increase the attractiveness of the Calendar Widget for a lot of users.

**Comment by yvolk** [comment]
This is that "Touchdown calendar" that should support Android de factor Calendar Provider API...
