### ISSUE TITLE
Support for TaskSync for Exchange 

### ISSUE THREAD

**Issue by mjt543** [plusonelabs/calendar-widget#137]
Have you considered supporting TaskSync for Exchange:

https://play.google.com/store/apps/details?id=de.cranktheory.android.tasks

Tasks and Notes for MS Exchange recently surprised users if its free app with a $10 license fee, and TaskSync is what I used before I started using your Calendar Widget, but switched to Tasks and Notes it wasn't an app your widget supported.

**Comment by yvolk** [comment]
Outdated issue
