### ISSUE TITLE
All day event issues

### ISSUE THREAD

**Issue by AnyoneThere** [plusonelabs/calendar-widget#146]
I entered a birthday as an all day event.  The date was set to only that date. When I saved it, it saved it for that date and the next date.  When I modify that event (selecting that event and all others), I get duplicate events occurring; that cover both days.  Currently, my screen has 4 bday events on one day and 2 on another for the same birthday.

**Comment by p-k-h** [comment]
Installed on: Samsung Galaxy Tab 4, Galaxy S5 Mini. Android 4.4.
Accessing a full day event from this widget and viewing the event in Samsung's calendar app, it shows the starting date a previous one as it is a two day event.
When editing this and saving, the starting date is changed to a previous, and it has become a two day event. Then if repeating this, it changes the starting date again to previous one, and the event is now a three day long etc.

**Comment by yvolk** [comment]
Fixed years ago...
