### ISSUE TITLE
Crashes if a calendar is deleted

### ISSUE THREAD

**Issue by denilsonsa** [plusonelabs/calendar-widget#148]
1. In your web browser create a new calendar (in https://www.google.com/calendar/ ).
2. Sync this new calendar to your Android device.
3. Configure this calendar in _Calendar Widget_.
4. Go to https://www.google.com/calendar/ and delete that calendar.
5. _Calendar Widget_ will now keep crashing on the device.

You might want to add some delay (like, waiting a few days) between those steps. But, essentially, I did these steps and now the widget keeps crashing.

**Comment by yvolk** [comment]
Outdated issue. Please raise a new request if you notice this in current version.
