### ISSUE TITLE
The horizontal lines are misplaced

### ISSUE THREAD

**Issue by VMIC92** [plusonelabs/calendar-widget#154]
Hi,
Actually, the horizontal lines separate the day from the event of this day. That generates a bad comprehension of the association beetween the day and his event. Beetween two lines we have an event and the date of another. It will be better to place this horizontal line to separate the pairs day-event from each to others.
Thanks in advance.

**Comment by paulle** [comment]
I support this the horizontal lines are misplaced, at a quick glance it's very misleading. It would be better that the event or appointment together with the date is inside the 2 horizontal lines.

Thank you for the beautiful widget.

**Comment by yvolk** [comment]
I agree, this confuses me also sometimes...

**Comment by paulle** [comment]
@yvolk can you fix it? Would be a great optical improvement.  I confused two times an appointment for this reason (know it's my fault).
Thank you in advance

**Comment by yvolk** [comment]
@VMIC92 @paulle @bushrang3r Done, at last :-)
![Screenshot_20190831-221922](https://user-images.githubusercontent.com/207716/64068253-4342ca00-cc3e-11e9-9be0-e2969190de97.png)

**Comment by bushrang3r** [comment]
@yvolk
Thank you sir! :)
That is a truly beautiful thing :)
Can't wait for the next update!

**Comment by paulle** [comment]
Thank you for doing this.

**Comment by yvolk** [comment]
Released in Beta version 3.0, please try: https://play.google.com/apps/testing/org.andstatus.todoagenda
Note: Due to lots of internal changes existing widgets should be recreated. Sorry for inconvenience.
