### ISSUE TITLE
Add a "Today" option on "Date Range".

### ISSUE THREAD

**Issue by robssp** [plusonelabs/calendar-widget#156]
Hi, 
I love this Calendar Widget. Thanks for the great job!
I´m wondering you could add na option "Today" in "Date Range". There are "One Day", "One Week", etc., and just "Today" would be very usefull.
Thanks and regards from São Paulo, Brazil,
Robson

**Comment by yvolk** [comment]
Hi @robssp, implemented in the latest commit, please check.
