### ISSUE TITLE
Recurring events disappeared

### ISSUE THREAD

**Issue by AnyoneThere** [plusonelabs/calendar-widget#159]
My reoccurring events were showing on my calendar until one of two things happened. Either I changed the reoccurring event to a different calendar name ('My Calendar' to 'BNI Calendar').  BNI Calendar is selected to be displayed on the calendar.  Or, from removing a couple of instances of the event because it occurred on the same day as Thanksgiving, Christmas and New Years.   For whatever reason, it is no longer appearing on my calendar.   Also, I changed the calendar back to 'My Calendar' and it is still not displaying on my phone's calendar.

**Comment by yvolk** [comment]
Too old issue to be investigated...
