### ISSUE TITLE
Calendar-widget development stopped - Call for a maintainer

### ISSUE THREAD

**Issue by yvolk** [plusonelabs/calendar-widget#160]
As you may see in the commit history, the last changes to the Widget itself were made on 2014-08-09 - almost half a year ago.
The application has feature requests and even pull requests (proposed implementations of new features), which are laying in the dust and discourage future development of this beautiful application. 

I think the time came for a new supporter to take this project over. So please consider this "issue" as a call for a new project maintainer (maybe a maintainer of a fork...)
I'm not proposing myself to this role, but I do have both ready to merge pull request and more ideas to be implemented, so I'm interested in the Calendar-widget development. 

What do you think?

**Comment by mpost** [comment]
Thanks for opening this issue @yvolk. 

As the sole maintainer of this project, recent developments have staled a bit since i had very little time to work on the project. The widget itself is very near to my heart as i use it daily and am quite pleased with the feature set it offers for my daily activity. The feedback and download numbers of the widget are very pleasing so, keeping it dormant should be avoided.

Therefore i would be very happy to see anybody pick up the current state and become a maintainer of the project.

**Comment by jkufner** [comment]
Or the calendar widget is finished and there is nothing more to do :)

**Comment by mpost** [comment]
@jkufner Well, my requirements are meat. :) But in fact we receive a few emails a week of people asking for more features. So there is a clear user interest. Of course not every request could and should be fulfilled.

In addition, the download numbers of the widget indicate quite a success.
Searching for "calendar widget" places this project neatly at number 2. of the search results: https://play.google.com/store/search?q=calendar%20widget&c=apps

**Comment by jkufner** [comment]
You should forward them to issue tracker to create feature requests
(with feature request label) for further discussion. Maybe someone will
implement it.

**Comment by mpost** [comment]
While it would still be great to have a new maintainer of the project, i just released a new version of the widget to the play store. :)

1.8.6 is life https://github.com/plusonelabs/calendar-widget/releases/tag/v1.8.6

**Comment by yvolk** [comment]
@mpost Do I understand correctly that that's all from your side?
I mean discussing pull requests, which wait since last summer etc. - will be "next maintainer's" work?!

**Comment by mpost** [comment]
@yvolk Dealin with pull requests is quite a lot of work. Also some of the features surpass the scope of the widget (from my point of view) so its hard to tell the people that they won't make the cut. But i'll go over them and leave comments.

**Comment by yvolk** [comment]
@mpost After rereading our conversations about [my proposed enhancements](https://github.com/plusonelabs/calendar-widget/issues/138) to the "calendar-widget", I see that what I proposed is really out of the scope of what _you_ think this application is about. Thank you for giving me a clue :-) 
So I decided to [duplicate, rename the repo](http://programmers.stackexchange.com/questions/188480/what-is-the-etiquette-of-renaming-an-open-source-fork) (in order to be able to publish my widget...) and start distributing alternative vision of the calendar widget...
The sad thing is that we will not be able to contribute to each other's projects easily (due to package  and application name changes...), but at least Users will benefit from having another Open Source Calendar widget alternative :-)

**Comment by mpost** [comment]
@yvolk I am happy to hear that you are so interested in the calendar-widget. Keeping the project going is great. While you could of course fork the project, i would much rather make you a commiter here so that this project can fruition in the future.

I would help you to publish releases to the play store while you could add features, basically making you the maintainer of the project. Would that be something you are interested in?

**Comment by yvolk** [comment]
@mpost I cannot promise my constant involvement in this project (and thus taking a "maintainer" role from You :-) ), but I really can take care of some enhancements including their development, testing and release preparation.
In fact, I did this already in my #138, excluding only version change in a Manifest and release notes in a changelog... I can do that also, so in order to have a new release/changeset, prepared by me, you need only to press button, accepting a Pull request, and build a new apk for distribution. Actually, pressing this one button for an automatic merge is not a hard thing for you, I guess :-) 
My understanding is that the main question in our cooperation is a degree to which you may delegate _responsibility_ for the code quality to me while accepting my Pull requests and not bothering with reviewing all the changes?!

**Comment by yvolk** [comment]
@mpost So, what or whom are we waiting for? :-)

**Comment by mpost** [comment]
@yvolk Yeah my fault. :) To simplify your life i will make you a commiter i suggest. I would than forward all the mails that come in for the calendar widget to you. Okay? :)

**Comment by yvolk** [comment]
@mpost   I do receive email notifications on the issues already. Private  emails are not efficient, I don't think we have time to answer each of them... 
Thank you for a commiter permission.

**Comment by plusonelabs** [comment]
@yvolk You are now a collaborator on this project. Welcome on board. :)

To keep you in the loop of user feedback we should forward user mails to you as well. No need to answer them all but it is good to see what people request (and complain about). Please send an e-mail to plus1labs@gmail.com indicating what mail address we should forward to.

So just to give you a rough idea... There are two issues people mention very often. We receive daily mails about them:

* https://github.com/plusonelabs/calendar-widget/issues/32
* https://github.com/plusonelabs/calendar-widget/issues/165

Anyways... Welcome to the team. If any more questions come up don't hesitate to contact us. :)

**Comment by yvolk** [comment]
@plusonelabs Thank you, it works! I couldn't resist starting from merging commits, authored last August. Looking at a result today I see that it needs more changes to improve UX; will do them.

As you asked, I created special email address to forward user mails on this application and sent the email to you. No mails so far :-)

I will definitely look at the issues you mentioned.
