### ISSUE TITLE
Please update the changelog

### ISSUE THREAD

**Issue by jondo** [plusonelabs/calendar-widget#162]
Could you please update the changelog in `README.md`? We are going to link to it in F-Droid.

**Comment by jondo** [comment]
Ah, I see that you are describing the releases [here](https://github.com/plusonelabs/calendar-widget/releases) now. So maybe the `README.md` should just link there?

**Comment by mpost** [comment]
@jondo Thanks for pointing that out. I have updated the changelog with the details of the 1.8.6 release.
