### ISSUE TITLE
Dragging the widget to the edit location opens app settings.

### ISSUE THREAD

**Issue by libor-m** [plusonelabs/calendar-widget#170]
Widgets can be dragged to the top of the screen, where there are 'Edit' and 'Remove' icons. When dragging calendar-widget, the edit icon is disabled. It should be enabled, and open the app settings on drop (which could be helpful in case of hidden widget header bar).

**Comment by yvolk** [comment]
What Android version your device has? What is a model? What Launcher application are you using?

**Comment by libor-m** [comment]
Android 4.4.3 in HTC one m7. The default launcher, don't know where to find
the name:)

**Comment by yvolk** [comment]
@libor-m Calendar-widget does have a Widget Configuration Activity,  which is not compatible with your Launcher for some reason. 
Do you know any OpenSource widget, which works on your phone as you expect?! We could look up there...

**Comment by libor-m** [comment]
I'm not using many widgets, so I'm not aware of any oss that would work. The only thing I found is http://stackoverflow.com/questions/11180671/re-configure-an-existing-appwidget, and it's not very helpful. I didn't know that the 'edit' button is not a standard android thing, sorry for that.

**Comment by yvolk** [comment]
Thank you for information, very interesting.
BTW, in a case of a hidden header bar you can configure the widget launching "Calendar Widget" application in a list of applications.
