### ISSUE TITLE
Feature request: Week numbers 

### ISSUE THREAD

**Issue by mabahj** [plusonelabs/calendar-widget#173]
First - great widget! It is perfect for my needs. 

It would be even better if it could optionally show the current week numbers. It could maybe fit to the right of the current day and date. Note that there are a couple of different numbering schemes (https://en.m.wikipedia.org/wiki/Week_number#Week_numbering)

**Comment by mabahj** [comment]
I should also have added a thank you(!)  for making this widget.

**Comment by yvolk** [comment]
Merging this with more general #216
