### ISSUE TITLE
Add option to hide event color

### ISSUE THREAD

**Issue by mark-tan** [plusonelabs/calendar-widget#174]
each event on the widget has a bar on the left that shows the event color. please add the ability to hide that. thanks!

**Comment by Ralf27** [comment]
I would appreciate that too. It would be great to be able to enable/disable the color of each calender additionally.

**Comment by yvolk** [comment]
In v.2.2 added the option: 
Layout -> "Show event icon" (Show Calendar color bar / Task icon for event). True by default
