### ISSUE TITLE
Option to keep passed current day events in the widget view.

### ISSUE THREAD

**Issue by Mahnas92** [plusonelabs/calendar-widget#175]
Add a customization option to make calendar events disappear on the end of the day they ended instead of the time they end.

**Comment by mpost** [comment]
This feature is coming in the next update. Please stay tuned.

**Comment by Mahnas92** [comment]
Nice!

**Comment by FredAntoun** [comment]
That will be great.  I guess I'm not the only one that doesn't do everything on time each day!

**Comment by yvolk** [comment]
Implemented in v.1.9
See "Show events that ended recently" option
