### ISSUE TITLE
Visually emphasize "Active events"

### ISSUE THREAD

**Issue by maiser2011** [plusonelabs/calendar-widget#178]
Would like to have an option of having active events show in a different color and/or size text.

**Comment by yvolk** [comment]
Do you call "Current" events (Now is between their Start and End times) "Active"?

BTW in the upcoming 1.9 release we will have custom color for _Past_ events.

**Comment by maiser2011** [comment]
Yes. Anytime the current time is between items start and end time that item could be highlighted by a different font color or in bold text.

**Comment by yvolk** [comment]
In v.3.0.5 (currently in Beta, see #320) different text shadings implemented for past, today and future. I.e. for Today you may change now not only background color, but text color also.

**Comment by yvolk** [comment]
We returned to this in 2015. see https://github.com/andstatus/todoagenda/issues/166
