### ISSUE TITLE
Calendar Color Selection

### ISSUE THREAD

**Issue by maiser2011** [plusonelabs/calendar-widget#179]
Would like better, more detailed options for changing individual calendar colors. Right now there are only a limited number of options with no options for variations of colors, i.e. lighter/darker, mixed colors, etc.

![image](https://cloud.githubusercontent.com/assets/13642835/9062784/17666b8e-3a8a-11e5-8580-c9c511ab6175.png)

**Comment by yvolk** [comment]
We are reusing existing component for color selection: https://github.com/LarsWerkman/HoloColorPicker
Do you know anything free and better?

**Comment by mjt543** [comment]
I use an app called "Set Calendar Colors" by One Rainboot Studios to alter the display color for all my calendars in the widget and the stock Android calendar. It also allows me to set the color for other items like those in the Tasks & Notes app that I have integrated with the widget. However, I could not find it in the Google Play Store for some reason to provide a link.

Date: Tue, 4 Aug 2015 09:47:46 -0700

**Comment by yvolk** [comment]
It doesn't look like Open Source or easily integrated with other applications (especially because this is a separate application...)
I think you may try to persuade the author of existing https://github.com/LarsWerkman/HoloColorPicker component to improve it, so our Calendar widget will benefit from this :-)

**Comment by yvolk** [comment]
Another not Open Source app that does this... https://play.google.com/store/apps/details?id=net.slintes.android.ccc.full&hl=en_US

**Comment by yvolk** [comment]
Looks like the easiest way to change a calendar's default color is in the Google Calendar App settings. I just tried!
See a screenshot in section 4 of https://www.computerworld.com/article/3390992/google-calendar-android.html

**Comment by yvolk** [comment]
Conclusion: Default Calendar color and colors of individual Calendar events should be set in the source Calendar app (see above example with Google Calendar). There is no need to duplicate it in this Widget.

The same applies to Tasks: Open Tasks app does have this feature also.
