### ISSUE TITLE
Feature Request: Tasks

### ISSUE THREAD

**Issue by kaneelias** [plusonelabs/calendar-widget#189]
It would be great if you could incorporate tasks so we can see what time a task is due on a day.

Something like TickTick would be awesome.

Cheers

**Comment by mjt543** [comment]
I use Tasks & Notes by UniqTec and it integrates with Calendar Widget beautifully.

**Comment by yvolk** [comment]
I use this option for tasks:
New "Show all past events having default color" optionshows all past events, which have 'Default color'. This option may be used to treat calendar events as Tasks and mark their completion by changing event's color. 
See #138 for a discussion.

**Comment by Apksde** [comment]
For my needs the widget is just perfect, but is there a way I could see my tasks too?

Thanks for your work.

**Comment by HPSysteme** [comment]
Totally agreed. Need the task too.
Thanks for this app.

**Comment by DirkBodschard** [comment]
Agree with this feature request. Would definitely an additional value.

**Comment by yvolk** [comment]
Implemented recently, see #308
