### ISSUE TITLE
Google events that repeat not showing 

### ISSUE THREAD

**Issue by Resurrection403** [plusonelabs/calendar-widget#191]
If you make an event that repeats, say a work week it only shows the current day... Not the following days. 
![screenshot_2015-08-25-16-39-52](https://cloud.githubusercontent.com/assets/13971498/9481487/0a8fbe82-4b48-11e5-8d92-f2f06d310eb9.png)

**Comment by mjt543** [comment]
This is not unique to Google. I use the stock Android Lollipop calendar and a recurring appointment I have each Wednesday shows up for the upcoming Wednesday but does not appear in the widget for subsequent Wednesdays.

**Comment by yvolk** [comment]
Hi all! I don't think that showing each occurrence of repeating event is the only correct behavior of a Calendar widget. 

BTW, I do see a  setting "Fill all day events", which as its summary says "Show an entry for each day of an all day event",  but there is nothing about showing each occurrence of repeating events.

So I think that current behavior is a feature, not a bug. I personally don't want to see e.g. "Work" repeating  event filling my whole widget and would prefer to see only one current occurrence (i.e. I like how the Calendar-widget works now). 

I agree that maybe this is not how the widget worked before, but I think that we need to add something like "Fill each occurrence of repeating event" setting  (Default to "yes" or "no" depending on what  majority of users would prefer..), not a hardcoded change.

What do you think?

**Comment by mpost** [comment]
I would agree that this is a bug. The expectation would be to see an entry for each repetition of an event. The option "Fill all day events" is unrelated to this particular functionality.

We could introduce a new option in an upcoming release to toggle that behavior but the default should be to show all repeated events.

**Comment by mjt543** [comment]
Thanks, @mpost. When I scroll the widget and don't see that second occurrence of the Wednesday appointment in my example, my natural assumption is that I have that time available for something else. If I have to keep remembering I really do have something recurring scheduled there, there's no point to the widget, or my phone's calendar for that matter :)

**Comment by ffes** [comment]
I fully agree with @mpost. Repeating events should be shown on all days. Sorry to say, but the new behavior is broken. I have something to do on that time and I should not forget about it or plan another event. And an option to change the default is fine.

**Comment by mpost** [comment]
We have fixed the issue and are now starting to make use of the public beta testing channel. Please feel free to opt in and see if the fix works for you: https://play.google.com/apps/testing/com.plusonelabs.calendar (might take a bit until the link becomes active)

**Comment by ffes** [comment]
Just became beta tester and got the beta instantly :-) The issue is fixed, thanks!!!

**Comment by mpost** [comment]
@ffes Good to hear. We will push the update to the stable channel today.

**Comment by mjt543** [comment]
+1 @ffes

Thx @mpost for the responsiveness!

**Comment by mpost** [comment]
@mjt543 Thanks for your feedback guys. :)

Btw... The 1.9.1 release has been moved to the stable channel by now.
