### ISSUE TITLE
Widget randomly becomes empty

### ISSUE THREAD

**Issue by scottb721** [plusonelabs/calendar-widget#196]
For no apparent reason the widget displays "No upcoming events" despite calendars still being selected and having events in them.

Cycling calendars off then back on restores events being listed in the widget.

**Comment by yvolk** [comment]
Could you try to press "Refresh" button on a Widget's header? Does this help to show events?

**Comment by scottb721** [comment]
I normally have the header hidden. I will reenable it and test that next time my events disappear.

Thank you
Scott


Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by scottb721** [comment]
The Refresh button restored the entries in calendar widget.


Sent from my Samsung Galaxy smartphone.


-------- Original message --------
