### ISSUE TITLE
Request: option to hide days in the past

### ISSUE THREAD

**Issue by volucris** [plusonelabs/calendar-widget#197]
Since recently, days in the past containing a multi-day event that has not been ended yet are listed as well. As a user I simply want to see what I have planned today and in the near future with as little scrolling as possible, and listing days in the past gets in the way of that. My suggestion is to provide the option to simply never show any days before the current.

**Comment by yvolk** [comment]
@volucris It's interesting why do you still have that multi-day events, if you don't want to see them even today?!
I mean you could simply change that events to e.g. one-day events and write information about their real duration in their Notes. 
BTW, currently Calendar-widget allows you to see this event in a list of past events, if you want  (if that event has Default calendar color).

**Comment by volucris** [comment]
I'm afraid I didn't manage to make myself clear there. I do want to see the multi day events, repeated on every day from today, but I don't need to see the past. Let's say I'm on day 2 of a 3 day meeting. Now it says yesterday: meeting. Today: meeting. Tomorrow: meeting. I want to see the last two, but not the first. I know what I did yesterday, and even if I didn't it's too late now anyway. Turning it yellow, blue or pink does not change that.

I hope this clarifies my issue, sorry for the confusion.

**Comment by yvolk** [comment]
Oh that bug / feature is already fixed, and may test it now building the application yourself from a Source code of this repository. 
So  this issue duplicates that: https://github.com/plusonelabs/calendar-widget/issues/184
