### ISSUE TITLE
Ongoing event shows wrong start time in 1.9.2 beta

### ISSUE THREAD

**Issue by mpost** [plusonelabs/calendar-widget#199]
Having an event from <code>9:00</code> to <code>12:00</code> on the current day, with the time being <code>10:33</code>, shows the start time of the event as the current time:

![image](https://cloud.githubusercontent.com/assets/73655/9830758/4d615388-593a-11e5-8139-bede9d764fbf.png)

The start time should instead be <code>9:00</code>.

**Comment by yvolk** [comment]
Yes, this is clear for event, which started today. 
But what do we expect to see,  if an event started yesterday at 9AM ?

**Comment by mpost** [comment]
Since it is a multi-day event i would expect to see an arrow: "-> 12:00 PM"
