### ISSUE TITLE
Secondary Calendars not Appearing

### ISSUE THREAD

**Issue by rubyjedi** [plusonelabs/calendar-widget#204]
For some reason, the Calendar Widget no longer shows any items from Google Calendars "Shared With Me" by family members, or from Secondary Calendars that I have created on my own account. (My primary calendar is set up for personal appointments; and I have a secondary for business appointments to separate the two)

Here's the daffy thing -- I have a couple of other Calendars "Shared with Me" that are also established as Public (calendars from my local MakerSpace is a prime example), and they are getting displayed just fine.

Has anyone else noticed or reported this issue?

**Comment by mootieman** [comment]
I've also got this issue. I'd love to see my wife's calendar as well.

**Comment by yvolk** [comment]
This is an issue of (or configuration task for) that Calendar application.
