### ISSUE TITLE
Events that carry over to the next day show as ending at midnight

### ISSUE THREAD

**Issue by yvolk** [plusonelabs/calendar-widget#206]
To reproduce the problem set an event starting today at 7pm to 7am the next day.

**Comment by yvolk** [comment]
Test case for this bug created and allowed to reproduce and fix the bug.

**Comment by mpost** [comment]
Fixed via https://github.com/plusonelabs/calendar-widget/commit/fd513872f35d376748f697ba50f36c9ed59c30c7

**Comment by Andy766702** [comment]
Brilliant, tested on my release and all works. Very prompt resolution. Thank you
