### ISSUE TITLE
All-Day Events Edit Error

### ISSUE THREAD

**Issue by 1965gtv** [plusonelabs/calendar-widget#213]
When selecting an all-day event via the widget, the date displayed is the previous date.

Actual date displayed on the widget is correct.
![a](https://cloud.githubusercontent.com/assets/15647916/10933999/c49c9b4a-8317-11e5-9c8e-7a675f0d3437.jpg)
![b](https://cloud.githubusercontent.com/assets/15647916/10934000/c4a408a8-8317-11e5-89a2-0ec853d7e63e.jpg)

Using Google Calendar to select the event, the date is of course correct.

Please see the screenshots. (Correct Date is Nov. 4)

**Comment by lexa1** [comment]
Same here. I have two events, all-day Event1 21.11.2015 and Event2 21.11.2015 21:30. They are displayed correctly in google calendar and on the widget, but if I click on Event1 it's date is 20.11.2015, if I click on it in the google calendar it's date is correct 21.11.2015. Date and time of the Event2 is correct everywhere.

{
  "results": [
    {
      "executedAt": 1448133935961,
      "selectionArgs": [],
      "sortOrder": "startDay ASC, allDay DESC, begin ASC ",
      "standardMillisOffsetUtcToLocal": 7200000,
      "projection": [
        "event_id",
        "title",
        "begin",
        "end",
        "allDay",
        "eventLocation",
        "hasAlarm",
        "rrule",
        "displayColor"
      ],
      "uri": "content:\/\/com.android.calendar\/instances\/when\/1447970400000\/1450725935960",
      "selection": "selfAttendeeStatus!=2 AND (calendar_id = 9 OR calendar_id = 8 )",
      "rows": [
        {
          "title": {
            "value": "Event1",
            "type": 3
          },
          "eventLocation": {
            "value": "",
            "type": 3
          },
          "allDay": {
            "value": 1,
            "type": 1
          },
          "displayColor": {
            "value": -11958553,
            "type": 1
          },
          "rrule": {
            "type": 0
          },
          "event_id": {
            "value": 1169,
            "type": 1
          },
          "hasAlarm": {
            "value": 0,
            "type": 1
          },
          "end": {
            "value": 1448150400000,
            "type": 1
          },
          "begin": {
            "value": 1448064000000,
            "type": 1
          }
        },
        {
          "title": {
            "value": "Event2",
            "type": 3
          },
          "eventLocation": {
            "value": "",
            "type": 3
          },
          "allDay": {
            "value": 0,
            "type": 1
          },
          "displayColor": {
            "value": -11958553,
            "type": 1
          },
          "rrule": {
            "type": 0
          },
          "event_id": {
            "value": 1170,
            "type": 1
          },
          "hasAlarm": {
            "value": 0,
            "type": 1
          },
          "end": {
            "value": 1448137800000,
            "type": 1
          },
          "begin": {
            "value": 1448134200000,
            "type": 1
          }
        }
      ],
      "millisOffsetUtcToLocal": 7200000,
      "timeZoneId": "Europe\/Kiev"
    }
  ],
  "applicationInfo": {
    "versionCode": 347,
    "preferences": {
      "showDaysWithoutEvents": false,
      "hideBasedOnKeywords": "",
      "eventRange": 30,
      "showPastEventsWithDefaultColor": false,
      "fillAllDay": true,
      "eventsEnded": "YESTERDAY"
    },
    "versionName": "1.9.3-35a0ac1"
  },
  "resultsVersion": 1,
  "deviceInfo": {
    "buildManufacturer": "Sony Ericsson",
    "versionCode": 16,
    "buildBrand": "SEMC",
    "versionCodename": "REL",
    "buildModel": "LT26i",
    "versionRelease": "4.1.2"
  }
}

**Comment by yvolk** [comment]
Actually, this is a bug of some "default" Calendar application, which is installed at your device. 
Calendar-widget doesn't have any "Editor" views. 
So solution to your problem will be changing this default Calendar application. See e.g. https://www.google.ru/search?q=android+how+to+change+default+calendar&oq=Android+how+to+change+default+ca&aqs=chrome.2.69i57j0l3.20362j0j4&client=tablet-android-samsung&sourceid=chrome-mobile&ie=UTF-8

**Comment by lexa1** [comment]
Yes, I know that calendar-widget doesn't have viewer or editor. When I click on event in widget it opens viewer of default calendar, which in my case is google-calendar. I also have agenda-widget installed (alternative to calendar-widget), and when I click on event in this agenda-widget it opens viewer of google-calendar and the date is correct. So it's a bug in calendar-widget or agenda-widget have a workaround for this.

**Comment by lexa1** [comment]
I see that calendar-widget provides begin and end times for default calendar viewer. Also I found this in documentation for "CalendarContract.Events": If allDay is set to 1 eventTimezone must be TIMEZONE_UTC and the time must correspond to a midnight boundary. Also found some one suggesting this code to resolve this issue:
intent.putExtra(CalendarContract.EXTRA_EVENT_BEGIN_TIME, from.withZoneRetainFields(DateTimeZone.UTC));
intent.putExtra(CalendarContract.EXTRA_EVENT_END_TIME, to.withZoneRetainFields(DateTimeZone.UTC));

Hope this helps.

**Comment by lexa1** [comment]
Here is the link: https://code.google.com/p/android/issues/detail?id=23852

**Comment by yvolk** [comment]
@lexa1 Thank you very much for pointing to a workaround of this Android  Calendar API bug. 
Actually,  this bug was reported several times (see e.g. #68, #146, #188), but only now we see a real cause and a way to a fix!
