### ISSUE TITLE
[Feature request] Padding after the last entry

### ISSUE THREAD

**Issue by nvx2004** [plusonelabs/calendar-widget#214]
Would it please be possible to add padding also to the bottom edge of the widget? In other words, could you please add the same amount of empty space after the last displayed item as is before the first one? Visually it would be much more pleasing than the current design, that is, the first item being nicely padded (https://cloud.githubusercontent.com/assets/6322455/11033249/febe6b82-86e1-11e5-9fc2-2ba58866bd22.png) and the last item virtually touching the bottom edge of the widget (https://cloud.githubusercontent.com/assets/6322455/11033264/19a328f2-86e2-11e5-96d5-e3243643b813.png).

Of course, this can only be encountered when there are enough items there that they either just fill the entire height of the widget or that there is more of them and as such scrolling is necessary to see the last item.

Thank you. :)

**Comment by mpost** [comment]
Valid request.

**Comment by ciarpame** [comment]
Hi,
I second this request: even if a minor detail, it would be a great cosmetic enhancement. Thanks!

**Comment by yvolk** [comment]
Padding in the form of an empty last entry, added in v.3.0, please try #320
