### ISSUE TITLE
In a day header show number of days from today

### ISSUE THREAD

**Issue by yvolk** [plusonelabs/calendar-widget#215]
Some users, including myself :-), are asking for the same feature: looking at a list of events we need to know quickly and reliably: how far are these events from today. 
I personally often find myself realizing that I don't remember, what day is today. And even if I know this  (not using this widget,  unfortunately,  because a date in the widget header is truncated, but this is another story...) I don't want to "calculate" the number of days: I just want to see it.

Regarding implementation, it's natural to (optionally) put this number at a left side of a day header.
Format: a signed number, e.g.:       -5   -0 (for past events) +0 (for current and future events)  +3
?!

**Comment by drojf** [comment]
I closed my issue as it's a duplicate of this issue.

**Comment by yvolk** [comment]
This old feature was implemented as a part of https://github.com/plusonelabs/calendar-widget/issues/42#issuecomment-289660073 and released two years ago.
Just select the "All in one row" Event entry layout, see https://github.com/plusonelabs/calendar-widget/issues/42#issuecomment-294288412

**Comment by drojf** [comment]
Ah, thanks. I think you can close your own issue then?
