### ISSUE TITLE
Day header date formats: Day of the week for today and tomorrow, Week number...

### ISSUE THREAD

**Issue by lexa1** [plusonelabs/calendar-widget#216]
Please change header of the day from "Tomorrow, 22 November" to "Tomorrow, Sunday, 22 November"

**Comment by yvolk** [comment]
We need to think about options for those, who ask for shorter text in date headers...
We have "Other settings" -> "Abbreviated dates" option that does an opposite to what we want in this issue.
Maybe transform that option into e.g. three values list "Day headers format" (should we have different format for a Widget header?!)

**Comment by yvolk** [comment]
As @mabahj suggested in #173, we need to consider another format: optionally include week number into the Day header.

**Comment by yvolk** [comment]
Another addition to Day header formats: 
As @virtualdj suggested in #336, we need an option to see number of days from today in the day header also. Currently we have "Today" and "Tomorrow only", but no any number for farther days.

Please note that we already have "Number of Days to event" option, but:
* it works only for "All in one row" event layout
* it shows number of days in a separate column, not in the day header.

**Comment by virtualdj** [comment]
I can suggest how Pure Calendar Widget (one of the best widgets IMHO, but it hasn't been updated for 3 years and this is the reason I'm looking here) dealt with this problem... It has some checkboxes to enable/disable today/tomorrow, week numbers and days left:


![01](https://user-images.githubusercontent.com/3251704/67159152-4fdfc680-f341-11e9-8a65-654ecaa3fb0f.jpg)


For the date format, there are **some presets plus** the **custom** setting, which displays a popup like this:


![02](https://user-images.githubusercontent.com/3251704/67159170-6b4ad180-f341-11e9-8bba-2a8f3813f2ac.jpg)


In this way, all the people can be satisfied.

**Comment by yvolk** [comment]
@virtualdj I thought about custom format string, supported by Android libraries, but hesitated to present them so far thinking that this could be too complicated for an ordinary User.
Looks like several presets + such custom formats will be the best way.
Maybe it would be good to include "Number of days to event" in such format also... if we are able to implement this...

**Comment by virtualdj** [comment]
> Maybe it would be good to include "Number of days to event" in such format also... if we are able to implement this...

Probably adding the week numbers and number of days option in the different presets would increment their number due to all the different combinations... So the date format is perfect while the on/off settings are better with checkboxes.

**Comment by val24** [comment]
Hello, 

I have hesitated to open a new issue or write a follow-up on this one. 

I like the new layout, but :

I like having day headers shown above all the events of that day.
I find having a column repeating days from today to event (which are all the same) a waste of space and a redundant information making reading more confused. 
I would much prefer having that information (which I find useful) in the day header - eg : Today Monday November 4 (week 45) / Tomorrow Tuesday November 5 (week 45) / +2 Wednesday 6 November (45) / Yesterday Sunday 3 November (44) / -2 Saturday 2 November (44).
An option to maintain the current event layout when day headers are not shown could be offered for people who prefer it that way.

**Comment by yvolk** [comment]
I created separate ticket https://github.com/andstatus/todoagenda/issues/7 for a reusable Preference dialog that we could reuse for setting of the Day header format also.

**Comment by yvolk** [comment]
Beta version with Date formatting preference released. See https://github.com/andstatus/todoagenda/issues/7 and download from here: https://github.com/andstatus/todoagenda/issues/3

**Comment by yvolk** [comment]
Released in v.4.0.6
