### ISSUE TITLE
Ability to change day header colour & event details colour

### ISSUE THREAD

**Issue by nvx2004** [plusonelabs/calendar-widget#218]
At this point one can only change the colour of the widget header and event titles. It would therefore be great if also the day header colour and event details colour were customizable -- at least in terms of the current "white", "light", "dark", and "black".

I guess that as of the current widget version both these colours are fixed to "light" but imagine the following: you have a rather light wallpaper so you do not want the widget background to be dark; instead, you want it to be light as well for which you could set the header/event colour to dark or black. Still, unless the background is almost-zero-transparency white this is not really possible because the day headers and event details are rendered in light colour no matter what and as such they are barely visible on the light-but-not-white widget background.

Thank you for considering this request.

**Comment by yvolk** [comment]
in v.2.2+ day header color ("Day header shading" option) changes separately from event text color.
![Screenshot_20190824-213235](https://user-images.githubusercontent.com/207716/64066515-8b082800-cc23-11e9-999b-2ee648aa80f8.png)
