### ISSUE TITLE
Make default notification time in settings

### ISSUE THREAD

**Issue by khaaa** [plusonelabs/calendar-widget#219]
Now if I set the Notification, then the time defaults to "15 min". But I often want "0 min". If it will be in setting it will be well for all

Thank you!

**Comment by yvolk** [comment]
This is defined by a particular Calendar application that you are using, not by the Calendar-Widget.
So please address this request to that application's team.

Tip: You may try different Calendar applications. Se  similar request ,which should be addressed by Calendar applications https://github.com/plusonelabs/calendar-widget/issues/238
