### ISSUE TITLE
Add support to show Reminders (shown in Google Calendar, Inbox, Google, or Google Keep)

### ISSUE THREAD

**Issue by CptanPanic** [plusonelabs/calendar-widget#220]
With Google inbox you can make reminders that show up in Google calendar. What is wierd is that it doesn't show on their calendar widget. Can this widget add support for this?

**Comment by donimo** [comment]
The most recent update to the Google calendar app added reminders as well. They show up in the Google calendar widget but not this app. Could you add support for this feature? I use reminders ask the time now and have had to go back to the Google widget to see them. I much prefer your widget though otherwise, thanks!

**Comment by yvolk** [comment]
Reminders are a very new Google feature. Today  I could find this support page on Reminders: https://support.google.com/calendar/answer/6285327?hl=en
This page has Android developers info on using reminders: http://developer.android.com/guide/topics/providers/calendar-provider.html#reminders
So technically this looks like doable.

**Comment by mpost** [comment]
The reminders feature gets requested a lot... Could be worth investigating.

**Comment by erikgeurts** [comment]
exactly, in #230 several people including me requested this.

**Comment by fmaylinch** [comment]
+1

Thanks for this excellent widget!

**Comment by PhysicsCodingEnthusiast** [comment]
Thank you for all of your hard work! Just wondering, is this a feature we can hope to get in the near future? It would be great! Thanks!

**Comment by Andy766702** [comment]
Would love to see reminders added. This app is so good.

**Comment by efbgirotto** [comment]
+1

**Comment by Lawnsweper** [comment]
Any sign of this feature being added ?

**Comment by fmaylinch** [comment]
I suggest to pay for this in advance, so the author can dedicate the time
to implement it. I'm willing to pay. Start a crowdfunding or something like
that. I'm serious.

**Comment by yvolk** [comment]
I re-read available documentation on Reminders at https://developer.android.com/guide/topics/providers/calendar-provider.html#reminders, created a couple of reminders via Google apps and it came to me that there is NO any documentation on the "Reminders”, about which we are talking here. 
I found recent discussion of the Google reminders in StackOverflow: http://stackoverflow.com/questions/35534774/how-to-read-reminders-in-google-calendars?rq=1
and it confirmed my suspicions: 

> The Reminders data seems to be held in a database accessible by the 'com.google.android.gms.reminders.provider.RemindersProvider' content provider.
Unfortunately, the provider is not exported and therefore is not accessible to third party apps.
Needless to say that the content provider is not documented and no public API exists.

Conclusion: showing Reminders (shown in Google Calendar, Inbox, Google, or Google Keep) cannot be implemented now in any reliable way.

**Comment by PhysicsCodingEnthusiast** [comment]
Thanks for the response! Is there any way for a developer (or us) to request a public API for this? Would really like to have this functionality in third-party apps.

**Comment by Nafania** [comment]
@yvolk  https://developers.google.com/google-apps/tasks/ isn't it documentation that you're looking for?

**Comment by ianrenton** [comment]
+1 from me, I would love to see this feature if/when Google makes the API available.

@Nafania I think that's something else, Google Tasks (https://mail.google.com/tasks/canvas) doesn't seem to reflect the Reminders on my calendar, or vice versa.

**Comment by Ahwaiz** [comment]
+1 for Google reminders. There appears to be no implementation of this feature in any 3rd party calendar widget app I've come across
