### ISSUE TITLE
Use space or commas in "Hide based on keywords in a title"

### ISSUE THREAD

**Issue by ElBeppologe** [plusonelabs/calendar-widget#223]
I would like to use space to filter out some appointments from the calendar. I don't know how to masquerade the space or comma so I could use it in the user interface. I tried " ' and () but nothin worked. 
For example: I would like to filter out events which contain _. Birthday_ but everytime I try this the _._ is seperated from _Birthday_
Thanks for the time

**Comment by yvolk** [comment]
Thank you for suggestion,  I just added the same filter enhancement to another project  ( https://github.com/andstatus/andstatus/issues/321 ) so it will be easy to add it to the Calendar-widget.

**Comment by sayash** [comment]
+1 for this :-)

**Comment by grafenhofer** [comment]
Our corporate calendar is full of events with a title like the following: "do it". Filtering for "do" and/or "it" is of course removing a lot of other events too. Allowing for more general filters would thus be highly appreciated. :)

**Comment by yvolk** [comment]
Implemented. Place a text in single or double quotes in order to have space or comma in a filter.

**Comment by yvolk** [comment]
To be released in v.1.10.0
