### ISSUE TITLE
seems the calendar cannot up to date automatically even enable the tool background running

### ISSUE THREAD

**Issue by o0oke** [plusonelabs/calendar-widget#225]
I always found the tool cannot auto update on the date task list, always need fixed by click setting button and back to the home screen to refresh the data again.

**Comment by yvolk** [comment]
Please see #120 , we created a separate Refresh button to a Widget header for this.
It works for me...

**Comment by o0oke** [comment]
Thank you. but what I want to see is the tool can always update date, or enable user to setting a auto sync period. so that the refresh button can be removed. or just enable drop down the task list to refresh, that looks more common action like I want to refresh my email in other apps.

**Comment by yvolk** [comment]
Recently I tried to figure out if the Calendar Widget refreshes automatically on my Android 6 tablet.
And you know: it does refreshes, but up to tens seconds after the event update. 
The refresh itself is instantaneous: I can see this using manual refresh button. So it looks like main Calendar application sends update notification with such a delay. Maybe, it does this after it has completed syncing this change with a cloud?!

**Comment by yvolk** [comment]
Please see a follow up on this problem here: #298
