### ISSUE TITLE
Add option to hide "No upcoming events"

### ISSUE THREAD

**Issue by E5823** [plusonelabs/calendar-widget#228]
Firstly thanks for a nice and clean looking widget. 

Precisely because it is so clean I would prefer the option to have the interface be completely empty when there are no upcoming events. The text display "No upcoming events" doesn't look good and to my mind is superfluous. It also has no function, i.e. pressing the text doesn't take you to calendar or anywhere. (Which I personally don't mind as I have another widget displaying also date that does this task.)

**Comment by homlett** [comment]
I'm totally agree with that. That would be very nice to be able to hide the "no upcoming events" message.

**Comment by jancborchardt** [comment]
It's absolutely not superfluous. When it's completely empty, it's indistinguishable from an error, so these empty content feedback states are needed.

**Comment by yvolk** [comment]
@E5823 Please see how it looks like in v.3.0 here: https://github.com/plusonelabs/calendar-widget/issues/282#issuecomment-536169071

Uninitialised widget looks differently, like here: #318
