### ISSUE TITLE
Google Reminders not supported/visible

### ISSUE THREAD

**Issue by fredphoesh** [plusonelabs/calendar-widget#230]
Google has rolled out it's new Reminders for Google Calendar... and IMO this aspect of Calendar really should be supported by the widget.

Thanks
Mark.

**Comment by kennethscott** [comment]
+1

**Comment by erikgeurts** [comment]
I would like to ask for support for reminders in the widget.

**Comment by saescott** [comment]
+1, reminders is very important.

**Comment by tomchiverton** [comment]
Just noticed this today

**Comment by magcsaba** [comment]
+1

**Comment by yvolk** [comment]
This is a duplicate of #220 
Please discuss there.
