### ISSUE TITLE
Widget Header day short form

### ISSUE THREAD

**Issue by dkg22** [plusonelabs/calendar-widget#231]
Given the restricted space in the widget header display (all that displays in a 2 of 4 column display on my front page - using the smallest text - is the first 7 letters only of the day). It should have the option of using the short form of day eg "Wed" which would allow room to also include the short form date instead of "WEDNESD" & no date display. Thanks

**Comment by adamdehaven** [comment]
Totally agree: Abbreviated dates (or a user option to switch to short dates) would be great

**Comment by kockok** [comment]
It would be great if the header contents are customizable such that I can only add a create event button on it.

**Comment by yvolk** [comment]
As I see the Pull request #233 actually didn't solve this problem, at least not fully: date in the *Widget header* is still not abbreviated. (Abbreviations appeared in "Day headers" etc. though...).
Fixing this now...

**Comment by yvolk** [comment]
To be released in v.1.10.0

**Comment by SubSi** [comment]
Unfortunately even the abreviated date is cut off in the header column when I use a narrow sized widget.
Maybe add small text size option for the header.
