### ISSUE TITLE
[Feature request] Open events/tasks in third party calendars

### ISSUE THREAD

**Issue by EleutheriusBliss** [plusonelabs/calendar-widget#238]
This is a very nice widget. It would be even more complete if there was an option to tap on events/tasks and have them opened in a calendar app of choice.
In my particular case (galaxy S5 international version, stock Android 6.0.1), there is no way to have the widget open existing events in Jorte calendar instead of the default S-Planner, that I dislike a lot because of its Lollipop (i. e. extra-white) style. I only can choose to add NEW events from the widget in Jorte.

**Comment by yvolk** [comment]
Android allows to clear Default application for many actions. Next time you will be prompted for an application to execute this action.
Use instructions like these (I just Googled them by ”android how to clear defaults”) :
http://www.greenbot.com/article/2151008/how-to-set-and-clear-default-applications-in-android.html
http://www.howtogeek.com/howto/43135/how-to-change-the-default-application-for-android-tasks/

**Comment by EleutheriusBliss** [comment]
Yvolk, thanks for the answer! Unfortunately, resetting default preferences for Android 6.0.1 apps on a Samsung S5 has no effect whatsoever on this widget. That is to say, tapping on an event will open S-Planner anyway.

**Comment by yvolk** [comment]
@EleutheriusBliss You could try to Disable the S-Planner application, at least temporary and check if Another Calendar application appears on Tapping an event.

It also could be that Jorte needs some other ”Intent” to appear as an alternative Calendar application...

**Comment by EleutheriusBliss** [comment]
I tried that too :-) in that case, tapping on an event prompted no reaction at all. If I had to guess, then I'd say the problem is not in Jorte, any calendar could not beat S-Planner on its "battlefield" without some "help" from the widget.

**Comment by yvolk** [comment]
On one of my devices (which has CyanogenMod) I have two applications that are suggested by Android system to open the tapped calendar event:
1. "com.android.calendar" - Open Source Android Calendar (it comes with the CyanogenMod).
2. "[com.google.android.calendar](https://play.google.com/store/apps/details?id=com.google.android.calendar)" - Google's extension of this calendar

I even installed these calendars, specially for this test:
3. https://play.google.com/store/apps/details?id=com.concentriclivers.calendar
4. https://play.google.com/store/apps/details?id=com.blackberry.calendar
5. Jorte https://play.google.com/store/apps/details?id=jp.co.johospace.jorte

- all calendars except Jorte, appear in a list of applications that can open the tapped event.
You can test this yourself.

Conclusion: the Calendar Widget does support third-party calendars. It doesn't support Jorte though. Or I would better say that **Jorte** doesn't support a way to open a calendar event that most popular calendars support.
BTW, a couple or years ago I tried to ask Jorte team of some changes - no reply. Then I joined _this_ project and uninstalled Jorte...
![screenshot_20160921-220820](https://cloud.githubusercontent.com/assets/207716/18725423/eaf23938-8048-11e6-8671-930a427265da.png)

**Comment by EleutheriusBliss** [comment]
Heck it worked! I had guessed wrong! I installed Digical (it has a dark theme in the free version, btw), and the widget let me choose to open events with it! Thanks a lot Yvolk! I think these instructions, with a warning for Jorte users, should be in the wiki.
