### ISSUE TITLE
Hide based on keywords in a title isn't working

### ISSUE THREAD

**Issue by chanceknguyen** [plusonelabs/calendar-widget#240]
Events aren't hiding on my Googe Pixel with this feature

![image](https://cloud.githubusercontent.com/assets/23022547/19633385/a8972b10-9976-11e6-8f15-8ea9c3e992bc.png)

![image](https://cloud.githubusercontent.com/assets/23022547/19633386/ae3a0290-9976-11e6-816f-50722bd58087.png)

**Comment by yvolk** [comment]
Keywords filter is case insensitive. I think this is why an event, containing "Cabin", was not filtered out
