### ISSUE TITLE
Events times change when changing time zones

### ISSUE THREAD

**Issue by mwilk84** [plusonelabs/calendar-widget#243]
Is there a way to make events stay on the same time in a new time zone? For instance, I have a reminder set for 7:00 a.m. every morning. But when I travel from Central US time zone to Eastern US time zone, I want to continue having that reminder at 7:00 a.m. local time but the app changes it to 8:00 a.m. instead. I tried the settings option to lock the time zone. This did make the reminder on my tasks last for the day move back to 7:00 but on the widget it's still showing as 8:00.

**Comment by yvolk** [comment]
We invented the "Lock time zone"  feature for this, but didn't implement it yet, see https://github.com/plusonelabs/calendar-widget/issues/201
