### ISSUE TITLE
Mishandling of All Day recurring events

### ISSUE THREAD

**Issue by lanri13160** [plusonelabs/calendar-widget#245]
I created an unending recurring all-day event for future events. I update these daily ("only this event") to reflect any changes. Using your widget, the updated event now spans two days. Using other calendar apps, it works correctly.

**Comment by yvolk** [comment]
Looks like this is a bug we discussed here: https://github.com/plusonelabs/calendar-widget/issues/213
?!

**Comment by lanri13160** [comment]
It seems to be the same, but the last entry in #213, from a year ago, appears to indicate the bug has been isolated and fixed? If that's true, I'm reporting that it hasn't.

**Comment by yvolk** [comment]
In order to fix this bug, we need to reproduce it first. So your help is needed to provide us with your case, which shows this bug.
Please send me ( or simply paste to this conversation) a report, generated via Calendar Widget Settings -> Feedback -> Share event for debugging
