### ISSUE TITLE
[Feature Request] Change calendar colors

### ISSUE THREAD

**Issue by fergusonbt** [plusonelabs/calendar-widget#246]
I would love to have an option to change the colors of the different calendars, or remove the colored tabs all together.

**Comment by tillig** [comment]
I found that if you change the colors in the web version of Google Calendar that the colors on the widget will sync to match.

The thing it doesn't cover is calendars that get added by apps. For example, the TripIt app can act as a calendar source and that color can't be synchronized with GCal. Same with calendars like local phone calendars.

**Comment by Rondom** [comment]
There are dedicated apps for changing the colours for calendar providers that do not support setting a colour.

I do not think this is an issue this widget is supposed to solve. It's more of an Android issue,I think.

**Comment by smichel17** [comment]
+1 to what @Rondom said. I use this app because it allows me to customize what events are displayed; allowing to modify calendars would only make it more complex and therefore less usable for me.

**Comment by wiggum333** [comment]
I agree that there should be an option to edit the calendar colors within the app/widget if you want to (or leave them alone) ... and just as important would be the ability to remove the calendar color markers in the widget completely.  I prefer the much more simple, clean look of just the text.

**Comment by yvolk** [comment]
v.3.0.5 (currently in Beta, see #320) has an option to hide calendar color bar completely.
Regarding changing calendar colors: this should be done in the corresponding Calendar applications.
See my comment with an example of how to change Calendar color in Google Calendar app: https://github.com/plusonelabs/calendar-widget/issues/179#issuecomment-524553612
