### ISSUE TITLE
Whole day events not correctly opened by the calendar-widget

### ISSUE THREAD

**Issue by ikerrg** [plusonelabs/calendar-widget#252]
I have seen that when you try to open an event that is defined for the whole day (no start/end times), if you open it directly by tapping on it in the calendar-widget, the event is spanned over two days (the day of the event and the day before). The problem appears if you try to edit it, as by default the event is changed to 2 days, and if you don’t realize that when you save it, the event is changed. However, if you open the same event by using Android’s calendar, the event seems to be correctly defined for only one day. I do not know if this is just a bug in the calendar-widget or if it only happens in combination with my system (Android 7.0 in a LG G5 smartphone). I am using the latest beta version 1.10.0-99d9a0f6.

**Comment by yvolk** [comment]
Before editing, do you see this event in the widget in one day only?
Could you reproduce this problem, 
make screenshot of the widget and post it here 
and send to me a report with events for debugging? (It's in Feedback -> Share events for debugging).

**Comment by yvolk** [comment]
I think I could reproduce the problem: it occurs when opening the All-day-event with a stock Android calendar (I have such on my LineAge/CM device).
But if I open the same event with Google Calendar, it shows it to me correctly.

So it looks like incompatibility/bug of some Calendar application.

In fact, all day events are quite weird (they don't have time zone... as I figured out a couple of years ago). So no wonder that different calendar applications interprete this differently... This is a consequence of badly defined API...

**Comment by ikerrg** [comment]
Thanks for investigating the issue. Yes, it seems that you have found the problem. If the calendar-widget opens the all-day event directly (using stock calendar app) it shows incorrect information spanning over two days (I do not use Google’s calendar). But if the event is opened from the stock calendar app without using the calendar-widget, the event is correctly placed in only one day. Do you think you can workaround the problem of the bad API to handle those requests correctly from the calendar-widget?

**Comment by yvolk** [comment]
I fixed this bug, now both Calendar applications open All-day events correctly.

**Comment by ikerrg** [comment]
Thanks, that was quick! I confirm it is fixed in the latest beta released in Google Play.
