### ISSUE TITLE
Calender date is shifted

### ISSUE THREAD

**Issue by atradwan** [plusonelabs/calendar-widget#254]
Hi, my calender seems to be shifted -1 day. All my events are showing 1 day earlier in the widget than what they show in Google Calender and LG Calender Apps.

The widget also shows Sunday, Apr 30 in the header but the first day shows Today, 29 Apr

**Comment by yvolk** [comment]
What version are you using now?
We do have Beta version in testing, please opt in here and check: https://play.google.com/apps/testing/com.plusonelabs.calendar

**Comment by atradwan** [comment]
Was on 1.9.3, but fixed after updating to the beta 1.10.0! Thanks!
