### ISSUE TITLE
Consider unique app name

### ISSUE THREAD

**Issue by JohnVeness** [plusonelabs/calendar-widget#256]
I think it would be a good idea if the app had a unique name, rather than just "Calendar Widget". At the moment it's hard to point someone accurately to your app by mentioning its name in spoken conversation (obviously easier electronically due to URLs).

If nothing else, maybe "+1 Calendar Widget".

**Comment by yvolk** [comment]
Maybe "Another Calendar Widget" ?!

**Comment by obperryo** [comment]
Maybe Calendar Instance Widget... Something that identifies it does
multiple calendars widgets, as that is a unique feature that not all
calendar widgets do.

**Comment by yvolk** [comment]
Since this year the app has the "ToDo Agenda" name. It's quite unique...
