### ISSUE TITLE
Outlook calendar is not available to select

### ISSUE THREAD

**Issue by Tjhartung** [plusonelabs/calendar-widget#257]
when selecting calendars to display my outlook calendar doesn't show as a available calendar to select. Not sure if this is a feature request or issue. gmail calendars show for selection but I would rather not need to sync outlook calendar with gmail.

**Comment by yvolk** [comment]
The Calendar-Widget user the official Android way to discover a list of calendars: it queries the "Calendar Provider" for this information ( https://developer.android.com/guide/topics/providers/calendar-provider.html )
In your case I would start from checking if other applications that use the same generic way to read calendars and their events, show your "Outlook calendar". See this post for a list of such alternative calendar applications: https://github.com/plusonelabs/calendar-widget/issues/238#issuecomment-248713796
