### ISSUE TITLE
How to add a themed Google Calendar to a widget

### ISSUE THREAD

**Issue by Vovusik** [plusonelabs/calendar-widget#260]
How to programmatically add to widget your own themed calendar created with Google Calendar (https://support.google.com/calendar/answer/37095?hl=en), which will be automatically preinstalled in the application, even without synchronization with the account.

Thank you.

**Comment by yvolk** [comment]
This looks like a question for StackOverflow :-)
The Calendar-widget application doesn't know, _how_ you created the calendar: if the calendar is shown in a list of calendars (available via android.provider.CalendarContract.Calendars#CONTENT_URI according to the Calendar API) , it will be available for display in the Calendar Widget.

**Comment by Vovusik** [comment]
Thank you.
