### ISSUE TITLE
[Feature Request] Tasks

### ISSUE THREAD

**Issue by djangothebest** [plusonelabs/calendar-widget#261]
Hello, would it be possible also to show the tasks?
I am using the Samsung G7 and I am using the standard google calendar and the included task function.

Thx

**Comment by digidream** [comment]
I vote for this function, too. There is currently no free widget showing both events and tasks. It used to work in Simple Calendar Widget, but the ability to show Tasks (using Dato's GTasks) stopped to work in never Android versions.

Honestly, do not understand how people can live without this.

**Comment by yvolk** [comment]
This request duplicates #242 
Please see it.
