### ISSUE TITLE
Wrap location field option

### ISSUE THREAD

**Issue by mattpanther** [plusonelabs/calendar-widget#262]
Every day I have meetings across many different conference rooms and the only way I can see the entire location right now is too use very small text. Would love the option to wrap location to multiple lines just like you have with title now. Would also me to see where I'm going at a glance, with a little larger text. For context I'm using a 2 column wide by 4 row tall size.

**Comment by sgserg** [comment]
+1 on this. Making subject/summary and location fit single line is just wrong: they have different type/importance. Also the stock widget (emulator image) uses slightly different fonts for summary and where/when (typeset difference emphasising difference in type?). Not sure if stock widget is the right reference, but it somehow looks good with 2 lines for summary, 1 line for location and 1 line for time (putting time on the right iOS style is actually a nice touch, albeit looking very cramped. Line spacing option might save the day...)

this one rather unusable:
![custom](https://user-images.githubusercontent.com/5439847/29291656-f5c7e258-814c-11e7-8d10-3736ab0f1361.png)

stock handling long summary gracefully:
![stock](https://user-images.githubusercontent.com/5439847/29291657-f5cbf672-814c-11e7-9c25-35728cdb345d.png)

even when made tiny:
![stock tiny](https://user-images.githubusercontent.com/5439847/29291771-4ded09d6-814d-11e7-82ac-a335313312f2.png)

**Comment by sgserg** [comment]
also, color bar being a space waste for single-calendar/type-of-events widget?

**Comment by yvolk** [comment]
@mattpanther The widget has "Multiline title" option for years! It allows to see the whole content, including the whole location string.
In v.3.0 (currently in Beta, see #320) text scaling in greatly improved: size of all text fields changes, not of the event Title only.

@sgserg Color bar can also be hidden in the v.3.0
