### ISSUE TITLE
Failed to refresh

### ISSUE THREAD

**Issue by hodbauer** [plusonelabs/calendar-widget#264]
On my MIUI Redmi note 4, with android 6.0 the widget refresh button do not work at all. Moreover, it not refresh automatically after an event has passed.

**Comment by yvolk** [comment]
@hodbauer It's interesting, as for your observation, when is the Calendar Widget list updated?

The Calendar Widget is updated by external events, presumably sent by a Calendar application or a "Refresh" button,
and also automatically once in 6 hours (as I see in https://github.com/plusonelabs/calendar-widget/blob/master/app/calendar-widget/src/main/res/xml/calendar_appwidget_info.xml )

**Comment by hodbauer** [comment]
@yvolk The only case that I'm 100% sure about it, is when I'm scrolling to the bottom of the list, then it refresh the list, and I've got updated.
 In any other case it's not for sure that i'll be updated.

**Comment by yvolk** [comment]
See and follow up in #298
