### ISSUE TITLE
"No upcoming events" shows even when loading

### ISSUE THREAD

**Issue by jancborchardt** [plusonelabs/calendar-widget#268]
Sometimes before the widget loaded, the emptycontent text is shown.

This is disconcerting and makes it seem like data is lost / events are gone. The empty content view should only be shown when there are absolutely no events to show.

For loading, of course there should be a loading spinner instead.

**Comment by yvolk** [comment]
Since v.3.0 we have a separate view for not initialized widget, please try #320.
See discussion in #318
