### ISSUE TITLE
Add month when title is disabled

### ISSUE THREAD

**Issue by Shadowigor** [plusonelabs/calendar-widget#269]
I try to have my widget as compact as possible, so I disabled the daily titles and moved the time to the same line. The only indicator of the date that is left only shows the day, but not the month. This looks quite weird and can also be confusing. There is also room left to add an abbreviated month.

Example:

![screenshot_20170924-115627](https://user-images.githubusercontent.com/6695660/30781522-6ce4e1f4-a120-11e7-998a-961a652c7f2e.png)

Note: As you can see, #236 applies here as well, those are all 1-day events.

**Comment by yvolk** [comment]
What you see is not a day of month, but number of days from today.
So following your logic you need both month and day on the same line.
This looks like what another user proposed recently: https://github.com/plusonelabs/calendar-widget/issues/333
