### ISSUE TITLE
Feature Request: Any click on the widget should just open the calendar app

### ISSUE THREAD

**Issue by ktaragorn** [plusonelabs/calendar-widget#270]
This would be an option which, when enabled, just causes all clicks on the widget to open the configured calendar in its default view, without the current behaviour of clicking on individual entries.

This is a recreation of  #150 to bring it up to date and reduce confusion

**Comment by yvolk** [comment]
This is too special request, I think: you already have a way to open a calendar app by clicking a title (even invisible) of the Widget Header.
