### ISSUE TITLE
Special color for "Today's Events"

### ISSUE THREAD

**Issue by wiggum333** [plusonelabs/calendar-widget#272]
I would love to see an option added that allows us to set a custom color for "today's events".  This is a feature of a calendar widget I used before, and it was one of the best features, as it makes it clear at a glance whether or not you have any remaining agenda events for that day, or if everything you're seeing in the widget is tomorrow or later.  Thanks.

**Comment by yvolk** [comment]
In v.3.0.5 (currently in Beta, see #320) different text shadings implemented for past, today and future. I.e. for Today you may change now not only background color, but text color also.
