### ISSUE TITLE
Events shift

### ISSUE THREAD

**Issue by diatel** [plusonelabs/calendar-widget#273]
After apply decret time all events in widget have one day shift. I.e. event 1st nov in calendar show as 31 oct in widget

**Comment by yvolk** [comment]
Every event has its own time zone. You can usually see the time zone if you open an event in some calendar application.
If you defined some event on November 1 00:00 AM at Summetr time, it will be on October 31 23:00 Winter time.
The calendar Widget may use current Device's Time zone, or its timezone can be locked, see https://github.com/plusonelabs/calendar-widget/issues/201
