### ISSUE TITLE
Add Event Entry Layout option for Time *Above* Title

### ISSUE THREAD

**Issue by bjweichel** [plusonelabs/calendar-widget#274]
Love the widget, thanks!

Can you add an option to the "Event entry layout" feature to allow putting the time above the title in addition to the existing option of time below title?

**Comment by yvolk** [comment]
We have Time AND Location on the same line (and actually in the same text field) below the title.
Moving this above Title doesn't look convenient unless you hide Location
?!

**Comment by yvolk** [comment]
Thisrequest is the same as in #167 Please follow up there.
