### ISSUE TITLE
Slows Down KISS Launcher

### ISSUE THREAD

**Issue by qoheniac** [plusonelabs/calendar-widget#276]
This widget fits very well together with KISS Launcher, but it slows down the search function. I don't know if this is a problem with this Widget or with KISS Lahncher, but I never had this kind of problem with other widgets.

**Comment by yvolk** [comment]
@qoheniac Please try recent version / beta here #320 
Is the problem still present?

**Comment by qoheniac** [comment]
The problem is gone. :)
