### ISSUE TITLE
Add ability to change appearance of Widget header

### ISSUE THREAD

**Issue by mpost** [plusonelabs/calendar-widget#28]

**Comment by yvolk** [comment]
In v.2.2+ we will have (in addition to old "Widget header shading"):
- two Widget header layouts (one and two rows)
- Widget header background color

See Two rows Widget header layout (with a new "Goto Today" button!):
![Screenshot_20190831-184219](https://user-images.githubusercontent.com/207716/64066577-492bb180-cc24-11e9-982b-674f41d1519a.png)
