### ISSUE TITLE
Allow option to hide date from widget header

### ISSUE THREAD

**Issue by PatrickWenk** [plusonelabs/calendar-widget#281]
The widget header displays the current day/date. It would be nice to be able to toggle the day/date off.

I use this fantastic app as a full screen widget on my pixel 2 xl home screen. The pixel 2 already shows the day/date at the top of the screen. Paired with the calendar widget the info is redundant.

I realize that I can hide the header all together however with the full header hidden I lose the ability to hit the plus icon to quickly add a calendar event, the refresh button and the widget settings access.

Thanks again for a fantastic app, it is easily the most useful tool on my phone as I always have a quick display of my work meetings and family events.

**Comment by yvolk** [comment]
The Beta 3..0.4 released, please check in #320
