### ISSUE TITLE
Change calendars display order

### ISSUE THREAD

**Issue by Cimbass** [plusonelabs/calendar-widget#287]
The order of all-day appointments and holidays is unfortunately a bit unfavorable for me at Google Calendar:
- All-day appointment
- Holiday
- Dates with time

I would prefer it in the widget:
- Holiday
- All-day appointment
- Dates with time

Therefore, it would be nice if you could change the order of calendars in the calendar widget.

**Comment by yvolk** [comment]
Implemented in v.3.1.0
Selected event source is moved directly below the last selected source, so a User can change the order of sources (Calendars, Task lists) by selecting them in the needed order.

This feature is mainly needed for #163 - to hide duplicated events.

**Comment by yvolk** [comment]
Testing on Pixel 3 device with Android 10

1. Before calendars and Task lists order change:
![calendars-order-001-widget](https://user-images.githubusercontent.com/207716/66555304-1b0c8c00-eb57-11e9-9f97-3393776931ef.png)
2. Corresponding settings:
![calendars-order-001-settings](https://user-images.githubusercontent.com/207716/66555357-31b2e300-eb57-11e9-92ed-074201a23114.png)
3. Now move "My tasks" one position down:
![calendars-order-002-settings](https://user-images.githubusercontent.com/207716/66555450-5e66fa80-eb57-11e9-9f3c-f1ece8898d16.png)
4. And see that "1. Check due tasks" event is below "2. Call me!" now:
![calendars-order-002-widget](https://user-images.githubusercontent.com/207716/66555626-a84fe080-eb57-11e9-9825-5b829f9518b9.png)

**Comment by yvolk** [comment]
Implemented in v.3.1.0, please check here: #320
