### ISSUE TITLE
[feature request] Set color and font size of every day title 

### ISSUE THREAD

**Issue by Ronin-Jay** [plusonelabs/calendar-widget#288]
I would like to change the color and the font size of every day title (today, 14.Mai / monday, 15. Mai / etc.)

**Comment by yvolk** [comment]
Do you mean e.g. 7 different settings for each day of week?

**Comment by yvolk** [comment]
In v.3.0.5 (currently in Beta, see #320) different text shadings implemented for past, today and future. I.e. for Today you may change now not only background color, but text color also.
