### ISSUE TITLE
Sometimes after pressing home button, the widget is empty

### ISSUE THREAD

**Issue by Offerel** [plusonelabs/calendar-widget#289]
Sometimes, when I leave apps like "forge of empires" or other apps and i press the home button on my Samsung Galaxy S7, the widget is empty. I must hit the little refresh symbol at the widget and then the content is displayed correctly.

Android 7.0.x 
April Patch

**Comment by yvolk** [comment]
Should be fixed in v.3.0, see #318 and please try from #320
