### ISSUE TITLE
Feature request: Hex code entry field for any of the appearance settings

### ISSUE THREAD

**Issue by vintaclectic** [plusonelabs/calendar-widget#290]
Nothing too pressing but I use your widget and has become my go-to app of a few for any new phone and widget always placed on home screen. Thank you for creating it and keeping it updated and working so nicely! 

If anything, I tend to be almost OCD like in my color choices for all appearance settings in apps and display on phones and no different across all my devices. I use three particular colors and can only get the exact ones via hex codes and not by the dial rotater used in this app. I've seen a couple apps simply just add a text field that automatically places dial to that exact color match. Either way, would just really love to see this feature to make things even more perfect than they already are with it in current state.

Thanks for considering adding this at some.point in future.

Regards,
V. Justice

**Comment by yvolk** [comment]
I'm adding this now, see https://github.com/plusonelabs/calendar-widget/issues/292#issuecomment-524551358

**Comment by yvolk** [comment]
Released in Beta version 3.0, please try: https://play.google.com/apps/testing/org.andstatus.todoagenda
**Note**: Due to lots of internal changes existing widgets should be recreated. Sorry for inconvenience.

**Comment by vintaclectic** [comment]
Thank you for adding this to your latest version, I really appreciate you!
