### ISSUE TITLE
White background not possible

### ISSUE THREAD

**Issue by meyerajm** [plusonelabs/calendar-widget#292]
There is no way to create an opaque white background in the appearance settings. The best you can do is a totally transparent light background. This is because moving "down" the spectrum of dark to light in any color is also the transparency control. Please separate transparency from color.

**Comment by meyerajm** [comment]
Ok,I figured out white. For others: the top slide bar is the darkness of the color and the bottom side bar is opacity.

HOWEVER: there is still no way to choose grayscale and have control over the darkness and opacity of that. Developers, could you add black to the color wheel (or beside it) so greys with customizable opacity are an option? Thanks!!!

**Comment by yvolk** [comment]
The Holo ColorPicker https://github.com/LarsWerkman/HoloColorPicker , used by our widget for years, confused many users, including myself :-)
This is why I decided to change the Color Picker to the more intuitive one: https://github.com/martin-stone/hsv-alpha-color-picker-android
As a bonus, we have:
- color previews in settings
- ability to reset any color to its default value
- manually set (copy) digital value of the color
...
![Screenshot_20190824-163910](https://user-images.githubusercontent.com/207716/63638241-609bf500-c68e-11e9-9632-e616c6919f22.png)

**Comment by yvolk** [comment]
Released in Beta version 3.0, please try: https://play.google.com/apps/testing/org.andstatus.todoagenda
**Note:** Due to lots of internal changes existing widgets should be recreated. Sorry for inconvenience.
