### ISSUE TITLE
Allow widgets to be removed from the settings

### ISSUE THREAD

**Issue by fredddii** [plusonelabs/calendar-widget#295]
I use Open Launcher and when I remove a home panel which contains widget, the widget settings remain in the application, eventually cluttering it with widgets that should no longer exist.

![calendar-widget](https://user-images.githubusercontent.com/15217150/46164669-e94bbe80-c28e-11e8-8a18-7a13d9802127.png)

**Comment by yvolk** [comment]
I checked the source code, and I see that this is not our widget ("ToDo Agenda" now) that remembers all widgets, but Android System that tells us, which widgets do exist.
```
    public static int[] getWidgetIds(Context context) {
        AppWidgetManager appWidgetManager = AppWidgetManager.getInstance(context);
        return appWidgetManager == null
                ? new int[]{}
                : appWidgetManager.getAppWidgetIds(new ComponentName(context, AppWidgetProvider.class));
    }
```
Our widget only stores its own view settings for the widgets, created and stored outside of it.

There is no programmatic way to delete widgets either.

So my conclusion is that the problem should be solved by figuring out, how to delete widgets in the app that created them, "Open Launcher" in your case.
I even would say that this is a bug of that launcher: it doesn't delete its own widgets properly.
