### ISSUE TITLE
No problem, only feedback

### ISSUE THREAD

**Issue by danjde** [plusonelabs/calendar-widget#305]
Hi Devs,
I'm using your fabulous widget on LIneageOS 15.01 and Nextcloud/Davdroid, no GAPS.
I would like to suggest little improvement for better usage:

1) option to hide/display setting menu, independently from today's day, that should have a specific and independent option to hide/show.
2) option to set different color for event present and future
3) option to set specific color for today's day.

That's all, and should be perfect!

Davide

**Comment by yvolk** [comment]
Thank you for suggestions, Davide.
Will add them to our TODO list.

**Comment by yvolk** [comment]
In v.3.0.5 (currently in Beta, see #320) everything from above is implemented. Including hiding date from the Widget header. 
See https://github.com/andstatus/todoagenda#v3.0 for the list of changes.
