### ISSUE TITLE
Calendar list is empty

### ISSUE THREAD

**Issue by stemy2** [plusonelabs/calendar-widget#309]
Hello,

I have many events in my agenda, but none of them is visible on the widget. When i try to choose a calendar via parameters, the calendar list is empty, even if the said calendars exists in Davx5 and ICSx5.

**Comment by yvolk** [comment]
The widget supports Android calendar only.
Apps that you are referring to, as I see, provide access to so other calendar types/interfaces... 
https://f-droid.org/en/packages/at.bitfire.icsdroid/

**Comment by stemy2** [comment]
I know it supported other calendars in the past, but one day, it stopped without apparent reason.

**Comment by stemy2** [comment]
Nope, it doesn't work with android calendar. I just activated it, and the calendar list is still empty.

**Comment by yvolk** [comment]
"Nope, it doesn't work with android calendar" 
As it does work for thousands of users, it should probably work at your device also. 
I don't know, what "I activated it" may mean, but if you use Android calendar, add events there, see these events via generic Android calendar app or Google calendar apps then the same calendar will be visible in the ToDo Agenda widget.

**Comment by yvolk** [comment]
@stemy2 For an example of compatible Android Calendar apps please see: https://github.com/plusonelabs/calendar-widget/issues/238#issuecomment-248713796

**Comment by stemy2** [comment]
I deactivated it because i wanted to use Etar. Now i just created an event with the android calendar app, and it still doesn't appear in todo agenda.

**Comment by yvolk** [comment]
The Widget uses this Android system service to get the list of calendars and their events: https://developer.android.com/guide/topics/providers/calendar-provider
In a case you managed to disable/turn this service off, the Widget won't be able neither get a list of calendars nor get events in these calendars.
Try to figure out, how to restore this.

**Comment by yennor** [comment]
I've got the same problem. The calendars I've got come in over DAVx⁵ (Caldav). No idea how they are stored on the phone. But every other calendar application I've tried out so far was able to find the calendars.

**Comment by stemy2** [comment]
@yvolk I reactivated everything, nothing changed.

**Comment by yvolk** [comment]
Another attempt to fix this is done, please check v.3.0.4 at #320
