### ISSUE TITLE
Calendar Widget Sync Delay

### ISSUE THREAD

**Issue by TheHungryGeek** [plusonelabs/calendar-widget#311]
Hi,

I've noticed that the widget takes quite a bit of time to sync any changes to the calendar.

Is there a way to tweak the sync duration? It could be a couple of hours and still not reflect the new events.

Thanks!

**Comment by yvolk** [comment]
Hi @TheHungryGeek First of all, please use the ToDo Agenda - the updated version of the widget.
It has a fix for the syncing. More details are here: https://github.com/plusonelabs/calendar-widget/issues/298
There is no any periodic syncing for now.
