### ISSUE TITLE
Date and event appearance confusing

### ISSUE THREAD

**Issue by bushrang3r** [plusonelabs/calendar-widget#315]
Days and events are separated by a line. 

Mon
__________________________
John's birthday
Tue
__________________________

As you can see, John's birthday looks like it's on Tuesday, but it's on Monday. It's visually confusing.

I think the event and the day should not have a line separating them as below.
_____________________
Mon
John's birthday
_____________________
This clearly shows that John's birthday is on Monday.

**Comment by yvolk** [comment]
I agree that current design may be confusing for somebody.
But that was designed many years ago and many users (including myself) are accustomed to this for a long time...

**Comment by bushrang3r** [comment]
Really? You agree that it's visually confusing, in other words, the UI design is flawed, but users are 'used to it' so you'll leave it as it is?  In my mind there is no question that it should be changed. To me, it makes absolutely no logical sense to leave it as it is. But, this is your app. 
Seriously, this is a deal breaker for me. I would scrap the other apps I use and change to this if it weren't for the UI.

**Comment by yvolk** [comment]
I don't think it's so simple. As I see in GIT history, this design was created more than seven years ago, and I don't remember similar complains yet.
This doesn't mean that this design shouldn't be changed. But this means for me that the decision shouldn't be taken lightly.

**Comment by bushrang3r** [comment]
I understand. Oh well, I don't suppose there will be anyone else coming in with the same opinion now if I'm the first one in 7 years. Shame.
Thanks.

**Comment by yvolk** [comment]
As you can see on this screenshot, today is easily visible in the upcoming versio 
https://github.com/plusonelabs/calendar-widget/issues/124#issuecomment-526298994

I will think about an option to have Day Header separator above the header text.

**Comment by yvolk** [comment]
@bushrang3r  I found an old issue that asks exactly for the same: #154 
So I think that I will change placement of the "Day header separator" without any "options"...

**Comment by bushrang3r** [comment]
Thank you〜
