### ISSUE TITLE
Add more values to "Show events that ended recently", up to one year

### ISSUE THREAD

**Issue by bushrang3r** [plusonelabs/calendar-widget#319]
Hello Yuri,
Now that you have me as a user, I'm gonna bring some more suggestions. Sorry :) hehe

Just like the time picker to choose future events, would it be possible to add the same time picker to choose to display past events?

**Comment by yvolk** [comment]
In the ToDo Agenda widget we do have these options for past events:
1. Filters -> Show events that ended recently
2. Filters -> Show all past events having default color.

Is this was you need? If not, please clarify / provide a screenshot...

**Comment by bushrang3r** [comment]
Unfortunately, 

#2 shows my events going back many years because it's just based on the colour.

#1 shows past events up until one day ago. 

I'd like to have the ability to choose to display past events going back 1 week, 2 weeks, 3 weeks etc. just like the future events option to choose a date range for future events.

**Comment by yvolk** [comment]
Not a problem, I will add more values to "Show events that ended recently".

Please note that option 2 allows you to mark ANY event as "done" by simply changing its color. Yes, to use this feature you need to change color of all past events first (or start using another calendar...) but after that you will see only those past events that need your attention. See https://github.com/plusonelabs/calendar-widget/issues/138

**Comment by yvolk** [comment]
@bushrang3r Implemented in v.3.0.3 (currently in Beta)

**Comment by bushrang3r** [comment]
Thank you sir! 
I can't wait for it to appear in on F-droid :)

**Comment by yvolk** [comment]
@bushrang3r Please test Beta version to help others getting quality release :-) https://github.com/plusonelabs/calendar-widget/issues/320
