### ISSUE TITLE
Clicking on day header opens the native calendar app instead of allowing to choose the calendar app

### ISSUE THREAD

**Issue by mpost** [plusonelabs/calendar-widget#32]
User Report:

when I click on a date ( not an event ) it always pops up the Samsung calendar app instead of a chooser of the installed calendar apps (where i can set which should open from now on).

It is a problem because I do not use the Samsung calendar app but an other. The bug appears only by clicking on the date, clicking on an event pops up a calendar app chooser as it should.

**Comment by earthsound** [comment]
This WFM with version 1.8.6 on a Galaxy S4.

**Comment by yvolk** [comment]
I just tested this on my Android 7.0 device after clearing all default for the Google Calendar application: clicking on a Widget Calendar prompts to select between the two "Calendar" applications, installed on my device. See the screenshot below.
