### ISSUE TITLE
Beta testing of ToDo Agenda

### ISSUE THREAD

**Issue by yvolk** [plusonelabs/calendar-widget#320]
Please note that the most convenient way for Beta testing is to opt in as a Tester at Google Play: https://play.google.com/apps/testing/org.andstatus.todoagenda
Unfortunately F-Droid doesn't have a notion of Beta release/testing yet...

If you don't use Google Play, for Beta testing I'm attaching the latest Beta release of _ToDo Agenda_ to this post.
The apk file inside the zip is signed with the same keys as in Google Play. I.e. in order to test the application you may be prompted to uninstall existing _ToDo Agenda_ application, downloaded from other sources.

Before installation of the below linked _ToDo Agenda_ package you have to unzip it first. This is .apk file that should be installed. I use "[Total Commander](https://play.google.com/store/apps/details?id=com.ghisler.android.TotalCommander)" for unzipping.

2019-10-12 v.3.1.1 Beta. Backup and restore Settings.
[TodoAgenda-3.1.1-546-release.zip](https://github.com/plusonelabs/calendar-widget/files/3721072/TodoAgenda-3.1.1-546-release.zip)

**Comment by bushrang3r** [comment]
Great! Thanks for the download link. I don't use google play.
Should we discuss the BETA in this thread?

**Comment by yvolk** [comment]
Yes, of course. Beta is public, so we can discuss it in public also, I think :-)

**Comment by yvolk** [comment]
No, not here, but in separate issues.
And please search for existing issues in order not to create duplicates.

**Comment by yvolk** [comment]
Closing this issue meaning that we solved a problem with Beta testing.
I will continue publish updates - Beta versions here though.
