### ISSUE TITLE
not an issue but a how to: transparent background

### ISSUE THREAD

**Issue by beng7** [plusonelabs/calendar-widget#321]
Hi
I was going to suggest a transparent background but realised that if, in Settings / 3 vertical dots in the widget > Appearance > Colors section - Background colour >  you slide the top scroll bar to the right and the bottom scroll bar to the left, you can achieve gradient transparency.
NICE!
posting for those looking for the functionality

**Comment by yvolk** [comment]
Please note that in version 3 (currently in Beta, see #320 ) we have another Color Picker in which making background transparent is much obvious to a User, I think :-)
