### ISSUE TITLE
Large space between icon/color and start of event text

### ISSUE THREAD

**Issue by bushrang3r** [plusonelabs/calendar-widget#323]
Currently, I'm not displaying start/end times and there is a large space before the event text begins. Would it be possible to have this space collapse if end/start times are not displayed? (Leaving only a small space e.g. the space of one or two letter characters)

Edit: for clarity

**Comment by yvolk** [comment]
Could you provide a screenshot, from which your case / your settings could be obvious (please edit your first comment for convenience).
Do you actually mean that you want Time column in the "All in one row" Entry layout to be hidden?! - we don't have such an option yet. We have "Show end time" only, but space is always reserved for start time as this is a table with columns...

**Comment by bushrang3r** [comment]
Yes, that's right. Hiding the 'time' column when the 'All in one row' option is selected. 

OK, I understand. It's a table.

**Comment by yvolk** [comment]
I could add "Show start time" to the top of "Event details" settings section?!
...lots of settings already...

**Comment by bushrang3r** [comment]
Oh! I just realised that if I select 'Time below title' the space collapses. That's what I wanted! Sorry, you can delete this issue....

**Comment by yvolk** [comment]
Good, closing
