### ISSUE TITLE
Settings options name changes

### ISSUE THREAD

**Issue by bushrang3r** [plusonelabs/calendar-widget#324]
Some settings options names are a little confusing.
Suggesting the following changes:

Widget header shading > Widget header text shading
Day header shading > Day header text shading
Event shading > Event text shading
Show events that ended recently > Show past events

**Comment by yvolk** [comment]
Thank you, I agree and will do this.
Let me know if you notice anything else.

**Comment by yvolk** [comment]
Done, in Beta now.
