### ISSUE TITLE
Event and background colors and shading problem

### ISSUE THREAD

**Issue by bushrang3r** [plusonelabs/calendar-widget#325]
There is only one setting for event text shading but different color options for event background, past event background and future background. 
This limits choices for background colours![image_2019-09-15_07-48](https://user-images.githubusercontent.com/5970120/64914564-b2b4cf80-d78f-11e9-9c83-0d32350021a9.jpg)

Perhaps some sub-menus in settings and more colour options would solve this.

e.g.

Settings | Colors | **Past**
> Day header text shading
> Event text shading
> Event background color

Settings | Colors | **Today**
> as above

Settings | Colors | **Future**
> as above

I agree there are already a lot of settings so perhaps there is an easier way to implement this....
Maybe day header text shading and event text shading could be just one option. ie. they are the same shading. This would create only 2 color options in the settings structure above, rather than 3.

**Comment by yvolk** [comment]
@bushrang3r Thank you for suggestions.

1. Regarding settings structuring and ordering.
As you may have noticed, I changed an order of settings in each section (mostly) to correspond to the order of elements on the screen: starting from Widget header and down... 
Similarly we do have "Past events" and "Current and future events" sections inside "Event filters". So I think that structuring Colors settings into "Past events", "Today's events" and "Future events" will be logical and will really help to find needed settings.

2. Regarding day header shading vs event shading.
I separated them only recently in #218. Previously Day header color was dependent on event color, but as some users noticed, is was always light and never black... 
Now we can set all widget text black or white thus adjusting for different backgrounds.

3. And finally: Why do we have "Text shading" with only 4 values and not continuous "Text color" with the same color picker as for backgrounds?
Actually "shading" means changing a "style", i.e. a group of attributes, together, including switching between white and black icons. See the four "Shadings" here: https://github.com/andstatus/todoagenda/blob/master/app/src/main/res/values/themes.xml

**Comment by bushrang3r** [comment]
OK, thanks. I understand.

2. The problem with this (as you can see in my screenshot) is that if my header text shading or event text shading is dark or black, I can't have any dark backgrounds for past, today, or future. They must all be light colours.

**Comment by yvolk** [comment]
@bushrang3r Yes, I see. So we need 2 * 3 text shading settings instead of 2.
I will do this.

**Comment by yvolk** [comment]
Done in v.3.0.5 Please check in #320 

In order to minimize number of settings the app hides color settings that are not actual.  It hides color settings for Day headers if "Show Day headers" setting is turned off. "Past events" section is removed completely if no past events may be shown and no task sources selected.

**Comment by yvolk** [comment]
@bushrang3r I like this extention so much that I even started to consider changing default today's colors. Previously all events where white text on dark background.
Now we can empathize today by inverting the colors. I found that such a change really makes today easily visible.
What do you think?
![Screenshot_2019-09-20-08-19-03-570](https://user-images.githubusercontent.com/207716/65301467-5c290600-db80-11e9-82ae-4124af69767e.jpeg)

**Comment by bushrang3r** [comment]
@yvolk 
Yes! It's wonderful! I love it. It's great to be able to show past, today, and future with different colours. Very easy and quick to differentiate events and days. It's very customizable now. I'll keep testing this beta and keep using it everyday. 
Thanks for all your hard work!
