### ISSUE TITLE
Request: add option for horizontal line placement

### ISSUE THREAD

**Issue by haakonhh** [plusonelabs/calendar-widget#326]
Hello Yuri,
Thank you for a wonderful widget! This widget is the single most important part of my Android phone!

But, since the 3.0 beta the horizontal lines in the day header was moved to a less ideal location. I can see that this was discussed in issue #154 (https://github.com/plusonelabs/calendar-widget/issues/154), but I think this looks worse now. The design element was elegant, but now it looks a bit clumsy, especially the first entry.

Maybe it is possible to add an option switch to this, so that we may choose to have the separator above or below the day header?

Thank you again for all your work!

**Comment by yvolk** [comment]
Hello Haakon, thank you for your kind words!
As you may have noticed, the discussion about Day header separator placement was drived by pragmatic goal: avoid User's confusion.
I was wandering, why the separator was places under Day header in the first place. And I think that found the source: I opened Settings of my Samsung Galaxy III (which is about 5 years old) and saw practically the same design. 
Since that time Android style changed greatly, and now that old theme looks outdated...

**Comment by haakonhh** [comment]
I think the line was more of an aesthetically line, and not a separator. More like the previous title style in Microsoft Word:
![wd10_select_style](https://user-images.githubusercontent.com/2139295/65610820-29cd3d80-dfb2-11e9-9dc5-1d7841843899.png)

I think it looked better before (sorry for the poor-quality image):
![IMG_0010](https://user-images.githubusercontent.com/2139295/65611002-7ca6f500-dfb2-11e9-9896-db0655cbbe7f.png)

Now it looks kind of broken, especially with the misplaced line on the very top:
![2097974980](https://user-images.githubusercontent.com/2139295/65611038-86c8f380-dfb2-11e9-9da3-7f11e4f3d5cf.png)

But, if the line will continue to be placed above the date, I will propose the following tweaks:
- Remove the very first line on the top.
- Add a few more pixels padding above the very first date header.

Thank you! :)

**Comment by yvolk** [comment]
> I think the line was more of an aesthetically line, and not a separator. More like the previous title style in Microsoft Word.

Yes, I agree. This is how we see it now :-)

I will easily hide the line in the first Day header, thank you for noticing.
I'm not sure how many actual pixels to add as its replacement. Any concrete suggestion e.g. using screenshot?!

BTW Did you notice that in recent Beta I added one-line empty element to the bottom of the list in order easily see that the list ends here... ?!

**Comment by yvolk** [comment]
@haakonhh I fixed current layout as you suggested AND added the new option "Horizontal line below Day header" as you originally asked for. Please try v.3.0.8 here: #320 

Tested this works even on Android v.4.3
![device-2019-09-28-094843-galaxy-s3](https://user-images.githubusercontent.com/207716/65812802-4b5a3f00-e1d5-11e9-8e16-3d07f82517de.png)

**Comment by haakonhh** [comment]
Sorry for mye late reply!

I have tested 3.0.8 now.
- Option for line below header is wonderful, thank you!
- Removal of the first line is very good. I think it looks good now. Enough padding on the top.
- The empty element on the bottom is good. I think there is no doubt that the list ends there.

Thank you again! :)
