### ISSUE TITLE
Today's event color overwrites previous event color

### ISSUE THREAD

**Issue by Clubby2010** [plusonelabs/calendar-widget#327]
I would like to see all previous events in yellow (even previous events from today).
I set show previous events which ended yesterday. 
The yellow color is shown for all events which ended yesterday but not for events which ended today.
In the previous version it was shown correctly.
I assume the new option for today's background color overwrites the previous events background color. For myself,I would like to disable today's background color.

**Comment by yvolk** [comment]
Yes, really. I remember I looked at the new "Today's color" feature and thought that something changed. But I didn't spot the difference :-)
1.See comparison of v.3 (on the left) vs v.1. Today's event is in the future:
![todays-colors-001-3-0-8](https://user-images.githubusercontent.com/207716/65826118-4a361a00-e288-11e9-9c0c-1928e8a90bde.png)

2. And this is how it looks, when one today's event is in the past:
![todays-colors-002-3-0-8](https://user-images.githubusercontent.com/207716/65826130-6f2a8d00-e288-11e9-8cc5-9fcbe6d993d9.png)

I agree that "Early morning errands" should be of past color.
But is it correct to show today's Date header in today's color also in this case: before event, having past color?
Looks like in the case 2 today's Date header should have Past color?!

**Comment by yvolk** [comment]
3. It becomes even more interesting in the case 3 below: I added "Three days meeting with d" that started yesterday and will end tomorrow:
![todays-colors-003-3-0-8](https://user-images.githubusercontent.com/207716/65826370-8cf9f100-e28c-11e9-9988-99412dfb567d.png)

Is everything on the right (v.1) correct? what we need to change now (on the left)?

PS: Why we don't see yesterday's part of the "Three days meeting with d" in both versions - is another story...

**Comment by Clubby2010** [comment]
Yes, for me the v1 Version was correct in all cases.
I wouldn't show today's header  in past color,this would be strange in example 3.
My default setting for showing past events is "ended today". In this,I would expect past events of today in the past color (yellow). Header, ongoing and future events of today in today's color (white).

**Comment by yvolk** [comment]
I made a fix. Will be published in v.3.0.9
![todays-colors-004-3-0-9](https://user-images.githubusercontent.com/207716/65829632-17078100-e2b0-11e9-9a83-e50451b0b112.png)

**Comment by yvolk** [comment]
The fix is published in v.3.0.9 Beta, please check here: #320

**Comment by Clubby2010** [comment]
I joined the google tester program,now it works,thank you

**Comment by yvolk** [comment]
In https://github.com/andstatus/todoagenda/issues/166 we are creating separate color option for ongoing events
