### ISSUE TITLE
v.3.0 Regression: Alarm and recurring icons aren't resized with text

### ISSUE THREAD

**Issue by yvolk** [plusonelabs/calendar-widget#328]
As @StarCruiser75 and one user at Google Play noticed, 
when we change text size, indicators (alerts and recurring events) don't change their size like in previous version.

Actually, as I see in the previous version indicators scaled down only, but weren't enlarged for larger that medium text sizes.

**Comment by yvolk** [comment]
Fixed in v.3.0.9, please check here: #320 
Smallest text size. 
![todays-colors-005-3-0-9-smallest-scale](https://user-images.githubusercontent.com/207716/65830656-0d831680-e2ba-11e9-9b7c-51c43d3275cc.png)
Medium size:
![todays-colors-004-3-0-9](https://user-images.githubusercontent.com/207716/65830664-2d1a3f00-e2ba-11e9-86c9-be96f0b53f77.png)

**Comment by StarCruiser75** [comment]
HI @yvolk , thank you for opening the separate issue, I was about to do it tomorrow as I'm traveling now.
Feedback on v3.0.9 is that icons are resizing randomly again with font size very small, depending on numbers of lines of the title (small if 1 line, big if two lines). With previous version they were always big.

**Comment by yvolk** [comment]
@StarCruiser75  I see that my current approach to scaling doesn't work in all Launchers... will need to try more...

**Comment by yvolk** [comment]
@StarCruiser75 Another fix in v.3.0.10, see #320

**Comment by StarCruiser75** [comment]
Very good! 👍🏻
Now icons resize correctly and all of the same size. Tested on three launchers.
Do you have a way to vertical align icons top instead of middle, as it does now?
Thanks

**Comment by yvolk** [comment]
> Now icons resize correctly and all of the same size.
,@StarCruiser75 This is because instead of trying to actually resize images now I put invisible images of three sizes into the widget layout, and make visible only relevant images :-)

OK will look into alignment. 
By the way, event text also alignes to the center vertically. I will need to change this also...

**Comment by StarCruiser75** [comment]
@yvolk don't get mad with alignment, it is only a suggestion, widget is now already perfect for me! ;-)
