### ISSUE TITLE
Cosmetical: all day event with location 

### ISSUE THREAD

**Issue by dAF2000** [plusonelabs/calendar-widget#332]
If you set an all day event and specify a location, it will show as:
[space] | [space] [location]

The "[space] | [space]" should be removed because this is only for events with a start time. Instead only "[location]" should be shown.

See also your screenshot on Google Play, here below:

![Screenshot_20191007_162655](https://user-images.githubusercontent.com/13932898/66320680-9552cb80-e91f-11e9-9062-1263f99adb6e.png)

**Comment by yvolk** [comment]
Implemented in v.3.1.0, please check here: #320
