### ISSUE TITLE
No more update on F-Droid ?

### ISSUE THREAD

**Issue by val24** [plusonelabs/calendar-widget#335]
Hello,
I can't find the latest updates on F-Droid. Is there a reason to that ?
Thanks

**Comment by yvolk** [comment]
Today, after two weeks of review v.3.0.11 was published in the F-Droid data repo.
More details here: https://gitlab.com/fdroid/fdroiddata/merge_requests/5561
Now we're starting to wait for a build...

**Comment by MaxXor** [comment]
Thank you @yvolk.

**Comment by yvolk** [comment]
v.3.0.11. is published on F-Droid https://f-droid.org/en/packages/com.plusonelabs.calendar

**Comment by val24** [comment]
Hello,
Thanks a lot.

Le jeu. 17 oct. 2019 à 20:19, Yuri Volkov <notifications@github.com> a
écrit :
