### ISSUE TITLE
Option to add number of remaining days on day header

### ISSUE THREAD

**Issue by virtualdj** [plusonelabs/calendar-widget#336]
Is it possible to add an option that changes the day headers from, for example:

`Monday 21 October`

to:

`Monday 21 October [+2]`

so that it's clear that the date occurs in 2 days from now? It's easier to visualize future events.

**Comment by yvolk** [comment]
This is another extension of proposed Day header formats #216, I added my note on this request there: https://github.com/plusonelabs/calendar-widget/issues/216#issuecomment-544219683

Design of Day header formats should consider all cases, so I don't think that we need a separate issue for Number of days to event in the Day Header. Please follow up there.
