### ISSUE TITLE
Sort all-day events alphabetically

### ISSUE THREAD

**Issue by udopt** [plusonelabs/calendar-widget#339]
I observed the following behavior: I added multiple all-day events to the same day of the same calendar (let's say "Test1", "Test3", "Test2", created in this particular order).

I would expect events to be shown alphabetically, but they are shown in the above order.

If sorting by time of creation is indeed the desired behavior, I would plead for an option to switch to alphabetical ordering.

**Comment by yvolk** [comment]
Hello @udopt I believe this such sorting was implemented recently (in v.3.1.2) Please follow up here: #112
