### ISSUE TITLE
[F-Droid build] Widget no longer shown in a list of widgets

### ISSUE THREAD

**Issue by stweller** [plusonelabs/calendar-widget#340]
Hi all,

I'm using the F-Droid build of the Agenda widget. Since the update to version 3, I can no longer find the widget in the list of widgets and hence I can no longer add it.

And yes, I did follow the instructions, remove the widget and reinstalled after rebooting.

Thanks!

**Comment by yvolk** [comment]
Hi @stweller 

1. I didn't test F-Droid's build before, but I did it now (on my Android 10 device) and everything looks OK.

2. If if you still have the problem please uninstall F-Droid's build and try my own from here: #320 

?!

**Comment by stweller** [comment]
Hi @yvolk ,

thanks a lot for your prompt reply. Indeed installing the build from #320 resolves the issue. But with the Android build, the app doesn't seem to be registering correctly; it is not visible anywhere.

My device is a Samsung SM-A520F (a5y17lte), with a Lineage OS 16 rom, i.e. Android 9.

**Comment by yvolk** [comment]
> But with the Android build, the app doesn't seem to be registering correctly; it is not visible anywhere.

@stweller I understand that you mean "F-Droid build" here?!

Thank you for the report. 
I will wait for other reports, maybe we will have to change application id in F-Droid...

**Comment by stweller** [comment]
Yes, sorry, I updated the comment. Never type faster than you can think.

**Comment by nkoester** [comment]
I too cannot find any widget in the list :( I am using Version 3.0.11-532 installed from the F-Droid store.  I use a Moto G (2014) alias titan with LinageOS 14.1 (7.1.2)

**Comment by yvolk** [comment]
@nkoester Please try suggestions, that I posted above.
?!

**Comment by nkoester** [comment]
Unfortunately, installing external APKs besides F-Droid is not an option on this device, sorry.

**Comment by yvolk** [comment]
I see you both use Lineage OS. 
It's interesting, is this incompatibility with it?
I need to test on some Lineage OS emulator, if such exists...

I think that the incompatibility is caused by the F-Droid's way to change declares app's package...

**Comment by stweller** [comment]
Well, if I can help by providing additional information, please let me know.

**Comment by stweller** [comment]
And by the way: Thanks a lot for putting extra effort into making the app work with F-Droid. It's very valuable to me to be able to install it without Google Play (and without manually downloading stuff)!

**Comment by relan** [comment]
> Do you think that we need to change the app's package in F-Droid to its 'natural' new one: org.andstatus.todoagenda?!

We can do that (i.e. add Todo Agenda as a new app). But I don't think app ID is the culprit. Just tested on my tablet with AOSP 8.1 with Launcher3: the widget is present in the widgets list and I could add it to a workspace just fine.

There's no LineageOS for the emulator (at least officially) and I don't have any devices with LineageOS at hand, unfortunately. @stweller, @nkoester, could you test Todo Agenda with a different launcher than LineageOS's Trebuchet?

**Comment by stweller** [comment]
Hi @relan , thanks for looking into this. I have seen other apps change their name without changing the app ID, so I tend to agree with you.

I deinstalled the manually downloaded app and switched to the F-Droid build again, and then tried adding the widget again. In Trebuchet, it doesn't work as before, but in OpenLauncher it does. Note that in contrast to Trebuchet, OpenLauncher doesn't offer a preview of the apps that it wants to add, don't know whether that is important.

Also note: This test may be not completely fair, because the F-Droid app is in version 3.0.11-532, whereas the beta version from #320 is at 3.1.7.

**Comment by yvolk** [comment]
@stweller The post in #320 has a history, where you can find any previous version, including v.3.0.11 (October 5): https://github.com/plusonelabs/calendar-widget/files/3693412/TodoAgenda-3.0.11-532-release.zip

**Comment by stweller** [comment]
Good point, thanks! I tried this version as well, and it does work in both Trebuchet and OpenLauncher. So basically, the only non-working version is F-Droid build + Trebuchet (which is unfortunately the combination which I would like to use...).

**Comment by yvolk** [comment]
I see that the only reliable way to fix such problems, caused by F-Droid specific builds (that aren't even tested before a release!) is to create in F-Droid new "ToDo Agenda" app with its native package name and no other changes from the app, build by myself, except for package signature (made by F-Droid).

I plan to drop support for Android before v.7.1.1 (API 25, the same as noted here: https://en.wikipedia.org/wiki/Android_version_history ), so it will be logical to leave old app for users with older devices.

**Comment by relan** [comment]
> This test may be not completely fair, because the F-Droid app is in version 3.0.11-532, whereas the beta version from #320 is at 3.1.7.

3.1.7 is now on F-Droid. Could you check it?

**Comment by stweller** [comment]
Yes, I checked, behavior is unchanged, i.e. the F-Droid build doesn't register a widget in the widget list and no app in the app list.

**Comment by yvolk** [comment]
@relan I decided to get rid of problems, caused by the app package name changes, and created the Merge Request with corresponding changes in F-Droid. 

Please review: https://gitlab.com/fdroid/fdroiddata/merge_requests/5983

**Comment by nkoester** [comment]
> > This test may be not completely fair, because the F-Droid app is in version 3.0.11-532, whereas the beta version from #320 is at 3.1.7.
> 
> 3.1.7 is now on F-Droid. Could you check it?

I updated to 3.1.7-560 from fdroid and the widget is now in the list! <3

**Comment by stweller** [comment]
Really? I'll re-check then later today.

**Comment by stweller** [comment]
Unfortunately I can't confirm. I'm still facing the same issues, as I described a bit earlier. Also in 3.1.7-560 from F-Droid nothing shows up for me (the manually installed apk works as expected).

**Comment by yvolk** [comment]
@stweller @nkoester ToDo Agenda with its original package name appeared on F-Droid site, please check:
https://f-droid.org/en/packages/org.andstatus.todoagenda/

**Comment by stweller** [comment]
Great, with the original package name everything works as expected now! It says "Unknown application" in F-Droid, but that's really only a cosmetic issue. Since the issue seems to be gone for @nkoester too, I'm closing this.
