### ISSUE TITLE
Too slow / no updates in F-Droid

### ISSUE THREAD

**Issue by val24** [plusonelabs/calendar-widget#344]
Hello,

Latest version of the widget on F-Droid seems to be 3.0.11-532 while GitHub Changelog mentions a 3.1.6 version. Is there a problem with updating apps on F-Droid ?

Thanks for your answer

**Comment by yvolk** [comment]
@val24 Yes, the publishing process is currently manual with a need to create PR for each change, wait for approvals etc. see the latest one https://gitlab.com/fdroid/fdroiddata/merge_requests/5561

But you could speed this up by preparing similar PR for the latest released version. 3.1.6
see #320

**Comment by val24** [comment]
Hello,
I'd really like to help, but I don't know how to do it. If you can explain
how I can do it, I will be really happy to help, but I don't even know what
a PR is.
Thanks for your answer.

Le jeu. 7 nov. 2019 à 16:34, Yuri Volkov <notifications@github.com> a
écrit :

**Comment by yvolk** [comment]
Oh, sorry, it is called "Merge Request".
This not for non-developers though :-)

**Comment by yvolk** [comment]
BTW, my next update is already 4 days in review... https://gitlab.com/fdroid/fdroiddata/merge_requests/5983

**Comment by yvolk** [comment]
The problem is even worse now, the latest discussion and links are here: https://github.com/andstatus/todoagenda/issues/31
