### ISSUE TITLE
[Feature Request] Move "days form today" into day header when displayed instead of column in each event

### ISSUE THREAD

**Issue by val24** [plusonelabs/calendar-widget#346]
Hello,

I like the new all in one row layout of the new version of ToDo Agenda (specially having event start and end time in a column in front of the event title.

But I find the column showing number of days from today redundant information if shown for each event when day header is shown.

It would be nice to have that information (number of days from today) :
- in day header when day header is shown - with column showing it in event informations removed
- in column in front of start and end time column (as it is now) when day header is not shown

Thanks

**Comment by yvolk** [comment]
1. You can turn the column off using its own setting now: "Show number of days to event".
2. Showing Number of days from today in a Day header will be covered by #216
