### ISSUE TITLE
Doesn't refresh 

### ISSUE THREAD

**Issue by jodidale** [plusonelabs/calendar-widget#349]
The refresh button on the widget does not work.

**Comment by yvolk** [comment]
@jodidale Please read this thread: https://github.com/plusonelabs/calendar-widget/issues/338
Is this your case?

**Comment by yvolk** [comment]
@jodidale Please try the latest Beta, it should refresh automatically! See #320

**Comment by jodidale** [comment]
It still doesn't refresh. Automatically or when I click the button. Using Google widget for now 😕

**Comment by yvolk** [comment]
@jodidale Oh, I see.
The problem that you encounter is not that Widget doesn't refresh, but that calendar data that Android system provides it via the "Calendar provider" service is not updated properly.
The widget simply gets outdated info on each refresh.
Please read my comments and tests discussion in the #338 .
