### ISSUE TITLE
Location and route based notifications

### ISSUE THREAD

**Issue by Sohalt** [plusonelabs/calendar-widget#350]
When an event has both a time and a location it would be cool to be able to get notified far enough in advance based on the current traffic situation to still make it in time. Specifically I'd like the app to repeatedly query how long it would take from my current position to get to the position of the event and if the start of the event is less than the travel time + some margin in the future I'd like to get a notification.

**Comment by yvolk** [comment]
@Sohalt These are all functions of a "Calendar app" (e.g. "Google Calendar"). This is the Calendar app that Notifies you, to the widget.

Our "ToDo Agenda" widget supports any Calendar app that allows to access its events via Android de-facto interface "Calendar provider".

So if your current Calendar app doesn't have features that you are asking, you can try to search for others...
