### ISSUE TITLE
Doubled / duplicate calendars events / tasks

### ISSUE THREAD

**Issue by luconsta** [plusonelabs/calendar-widget#354]
Hello,

I don't know if the last updates breaks it, but I suddenly see doubled tasks in the calendar widget. I have selected a single calendar and still doubled the tasks.

Kind Regards,
Lucian

**Comment by luconsta** [comment]
Hello Yuri,

Thank you for your time. As I said in my initial message - I have selected a single calendar and the appointments are still doubled.

The other option to "hide duplicates" I could not find it. It could be the language of the phone? What other option I have tried is to clear cache and data for that widget and reconfigure but the problem persists.

One thing to mention: It seems that new planned events are not doubled - just the events registered/entered in the past week recurring or not. The only option I did not try it yet was to uninstall and reinstall the widget but the link tapped in widget to the Play store is broken.

Any other suggestion?

Kind Regards,
Lucian

**Comment by yvolk** [comment]
Hello @luconsta 
1. Are you really using the latest app version? Please install from https://play.google.com/store/apps/details?id=org.andstatus.todoagenda and check above advises once again (uninstall, reboot, install may be required...)

2. If above doesn't help, please do this:
2.1. Please email me report (actually JSON text), created from "Feedback and Backup" - "Share events and settings for debugging" You may apply filters and show only fake events... 
2.2. + attach screenshot of what you got that shows events duplication.

**Comment by luconsta** [comment]
Hello Yuri,

Indeed it was an old version, but the new version crushes constantly. I have send an report from my phone and maybe the attached log may help.

I had the chance for couple of minutes to try the previous recommendations:
1. "Event filters" - "Hide duplicates" - did not help - still duplicates
2. Try to turn off some calendars in Settings: I have tried with a single calendar and still have duplicates.

For the moment I cannot use the "Share events and settings for debugging" because is crushing... Even after another deleting and reinstalling... :(

**Comment by yvolk** [comment]
@luconsta  I see that the widget may crash if "Hide duplicates" option is set.
Please turn it off and you will be able to send the report to me (and don't forget about a screenshot!)

**Comment by NLLAPPS** [comment]
This happened to me too. I have tried your duplicate filter suggestion but it did not work. I had my exchange account syncing calendar with Samsung Email app. 
What worked for me is to deleting and re-adding the account.
However, I cannot be sure if that's what helped as I was randomly trying enabling disabling sync etc. around the same time.

**Comment by yvolk** [comment]
@NLLAPPS If you see the same problem again, please create a report in Feedback and Backup" - "Share events and settings for debugging" and corresponding widget screenshot.

**Comment by yvolk** [comment]
I made a fix to avoid crashes during duplicates hiding, plus maybe this duplicates hiding may be improve. Please test, see #320

**Comment by NLLAPPS** [comment]
Will do
________________________________
