### ISSUE TITLE
Task refresh issues

### ISSUE THREAD

**Issue by dylanrees** [plusonelabs/calendar-widget#359]
Hello,

I'm noticing that when I update my personal calendar, the changes sometimes don't appear in the calendar widget, even when I hit the refresh button.  I'm running v3.1.6 on Android PDS29.118-15-11.  Problem persisted for a period of time even after a system restart.

**Comment by yvolk** [comment]
Hi,
Is this about Tasks or Calendars?
If about tasks, please read https://github.com/plusonelabs/calendar-widget/issues/338

**Comment by dylanrees** [comment]
It was about Calendars, thanks!
