### ISSUE TITLE
"Show all past events having default color" makes more events show

### ISSUE THREAD

**Issue by filigranen** [plusonelabs/calendar-widget#362]
I enabled, under Event filter > past events, the setting "Show past events" and set it to "Ended today". Works fine. Not sure it is related, but that's what I did. 
Then I enabled the setting "Show past events having default color", and it showed events it didn't before. Mostly birthdays, for some reason.. Disabled it again, and all is back to normal. 

I recorded a video showing what happens: https://youtu.be/a_denisORtE

On a Huawei p20, Android 9.1, todo version 3.1.9-565.

Let me know what else I can provide information wise.

**Comment by yvolk** [comment]
Hello @filigranen .
This is how the feature should work. If "Show past events having default color" is turned on, in order to hide any past event you need to change its color to some other color. This feature was invented to allow a User explicitly mark calendar events as completed/done, just like we usually do to mark tasks as done.
See #126 and #138

**Comment by filigranen** [comment]
Oh. Now that I see the reason for the setting I understand the meaning of the word "having" in that sentence. I thought it was just an oddly written string that should read along the lines of "Show past events using default color", in other words dont use the color set in colors > today event background color. 
I have that set to red, I thought this would make ended events show using the regular calendar color. Since they are under the same heading I thought they were related. 

Is there a setting for that btw? Showing today's ended events not using the set today color. To easier distinguish what is still important.

**Comment by yvolk** [comment]
@filigranen As you can see in #138 some years ago I wanted to add the option "Show past events of specific color(s)". 
But at that time after discussions we ended up with another option: "Show past events having default color". I see that the later option is not convenient if you want to mark only a few events as important and needed to be shown even in the past.
So we can think about adding the option now:  "Show past events of specific color"...

**Comment by filigranen** [comment]
@yvolk
I have never changed the color of an event to make it complete. To me that is a cumbersome way of doing things. That would mean I had to change color of all my events when they complete to get them to go away from the widget? Why not snooze them or change the Event time? 

IMO it would make more sense to do the opposite: if I want something to show regardless of if it is ended/completed I change its color and the setting is "Show events NOT having default colors". That way the two settings would be related: set it to show events X days back and it shows all events X days back. Set the color setting and it only shows them if they have an edited color. Not like now, when all my events back to 2008 are shown even though I set it to show ended today.

It's just that I thought it had something to do with the today color alterations or other color related settings. 
Since it doesn't, I wont use the feature no matter how it's formulated. And since I am the only one to mention it in a few years, I guess it's just me. 😋

**Comment by yvolk** [comment]
I think that I will change currently available "Show all past events having default color" checkbox option to
"Show past events having default color" with a list of periods. So we won't need to change color for too old events in order to hide them.
?!

**Comment by filigranen** [comment]
Sounds like it can't hurt to be able to hide events from years ago.

Also, it seems that the events for today are already shown with their default colors when they have ended. So all is well now. 

Never should have touched the setting, to save you some work. 😋

I'll close this then as it feels resolved. 👍
