### ISSUE TITLE
Widget home screen unresponsive

### ISSUE THREAD

**Issue by zombypc** [plusonelabs/calendar-widget#366]
After putting widget on home-screen I can't click on the widget to either edit the widget, view the calendar, add to calendar, refresh calendar. (basically it's non interactive).

Using MIUI 11 based on Android 10. 

Not sure if this is related to my other issue #365

**Comment by yvolk** [comment]
General advise is to restart your device. See the changelog note: https://github.com/andstatus/todoagenda#changelog
