### ISSUE TITLE
[Beta] Future events not respecting selected time period

### ISSUE THREAD

**Issue by bushrang3r** [plusonelabs/calendar-widget#367]
Beta 4.0.12-674

When I select one week for past and future, one week in the past is correct, but one week in the future is not one week, and it doesn't add one day each day, so after one week, there are no more future days or events. 
If I set future events to one month, it only shows three weeks.
I guess the widget is not reading the calendar storage correctly. I use a 'local calendar storage' app. Maybe the problem is with that app. It hasn't been updated for a while.

Edit: I've just discovered that the offline calendar app has been integrated into Etar calendar. I will try it and report back.
https://github.com/SufficientlySecure/offline-calendar

**Please disregard the info below until I have tested Etar calendar.**

This log file shows one week past and one month future.[Pastebin log file](https://pastebin.com/D0i3EiPf) 

This image shows one week past and future.

![Screenshot_20200403-233537_Lawnchair_1](https://user-images.githubusercontent.com/5970120/78376292-10fcaf00-7609-11ea-80a6-871141f4b1e3.png)

**Comment by yvolk** [comment]
@bushrang3r Thank you for the report, let's continue discussion here: https://github.com/andstatus/todoagenda/issues/20
