### ISSUE TITLE
Task: Astrid Clone - deleted tasks still show in the widget

### ISSUE THREAD

**Issue by jimfum** [plusonelabs/calendar-widget#370]
Steps to reproduce:

1. Click 'add task' button on the Agenda widget which takes you to the Task window. Just enter the task name, nothing else and save.
2. The task appears on the Agenda widget (after refresh) as well as Task widget.
3. Click the task name on the Agenda widget which takes you to the Task window. Delete the task there (delete, not mark as completed)
4. Refresh the Agenda widget - the task is still there. The Task widget doesn't show the task anymore as expected.

Workaround:
Click the task again on the Agenda widget. The task is opened in Task window - click Complete instead of Delete to remove it from Agenda widget after refresh.

**Comment by yvolk** [comment]
Hello @jimfum 
Thank you for the report.

However, current ToDo Agenda Issue section is here: https://github.com/andstatus/todoagenda/issues ,
so please create new issues there.
Regarding this concrete issue though, I think that this is the Tasks app bug to provide deleted tasks to our widget (ToDo Agenda widget doesn't store events anywhere). And so this should be reported there: https://github.com/tasks/tasks/issues
