### ISSUE TITLE
Birthdays are missing?

### ISSUE THREAD

**Issue by minlength-is-0** [plusonelabs/calendar-widget#371]
My widget does not show any birthdays, for which I could not find any option in the settings. I feel like remembering that a year ago or so the widget showed me birthdays. Feel free to correct me :)

**Comment by yvolk** [comment]
Hi @minlength-is-0 
Are you still using the Calendar-Widget app or you migrated to ToDo Agenda?
In the latter case please look at similar questions here: https://github.com/andstatus/todoagenda/issues/68

**Comment by minlength-is-0** [comment]
> Hi @minlength-is-0
> Are you still using the Calendar-Widget app or you migrated to ToDo Agenda?
> In the latter case please look at similar questions here: [andstatus#68](https://github.com/andstatus/todoagenda/issues/68)

Still using the Calender-Widget but now migrated to ToDo Agenda and everything works like a charm. Thanks
