### ISSUE TITLE
Choose default calendar app

### ISSUE THREAD

**Issue by fortewu** [plusonelabs/calendar-widget#376]
Is there a way to change the calendar app that an event opens. Right opens samsung calendar would like to change to google.

**Comment by yvolk** [comment]
Hi @fortewu 
Please note that the "calendar-widget" app is replaced by the "ToDo Agenda" app (see https://github.com/andstatus/todoagenda#readme )

The problem that you encounter is discussed in this issue: https://github.com/andstatus/todoagenda/issues/23
