### ISSUE TITLE
Deleted repeatable event does not disappear from the widget

### ISSUE THREAD

**Issue by bushrang3r** [plusonelabs/calendar-widget#379]
I am on version 4.8.0 of ToDo Agenda.

When I delete a repeatable (recurring) event, it disappears from my calendar but it does not disappear from the ToDo Agenda widget. 
(I deleted just one occurance of the repeated event, not all of them)

I cleared the storage of ToDo and started again, but the deleted event is still there. 

The last 2 versions of ToDo did not have this problem for me but I remember having this problem a few versions back but do not recall which version it was.

**Comment by yvolk** [comment]
Hello @bushrang3r 
ToDo Agenda's issues are in its own Github section... Regarding not disappeared events please see the related discussion: https://github.com/andstatus/todoagenda/issues/17
