### ISSUE TITLE
Allow the user to select the range in which the dates are shown

### ISSUE THREAD

**Issue by lu-w** [plusonelabs/calendar-widget#39]
It would be awesome if it was possible to select an option like "Show all dates up to 60 days" or "Show all dates set for the next three months". For some people with less frequent dates in their calendar (but who like the possibility of displaying them in a widget) this feature would be great. At the moment I am able to see exactly one date (which is set in the next month).
I would like to see this implemented!

**Comment by kockok** [comment]
How about adding "3 days ahead" in Date Range? Or just create a "custom setting", for instance, some may want "2 days ahead". Thanks.
