### ISSUE TITLE
Allow to display an event in one line (with time possibly appended)

### ISSUE THREAD

**Issue by mpost** [plusonelabs/calendar-widget#42]

**Comment by yvolk** [comment]
This request is repeated e.g. "...And finally again to save vertical space, the option to move the time in the same line as the event title, thus making the events single lined"

**Comment by yvolk** [comment]
I implemented this long-awaited feature by adding new "Appearance -> Event entry layout" option, which currently allows selection between: 
* "Default multiline layout" (i.e. leave everything as as it was before this change) and
* "Single line layout" - this new one.

The new layout works with recent contribution of the "Show day headers" setting, which allows to optimize vertical space even further: when day headers are turned off, a date is added to each event's line automatically in the first column. Currently only one format is available for this date, which I personally love :-)  - relative date, i.e. "-2, Yesterday, Today, Tomorrow, 2, 3, ...", which is very clear and far quicker to comprehend than longer date formats...

Please see the screenshots below.
1. Initial state: Default multiline layout, day headers are present. "End time" is turned off. "Multiline title" is on.
![default-layout](https://cloud.githubusercontent.com/assets/207716/24329099/d468f7b2-1204-11e7-808c-b9c7a160bf0a.png)

2. Switched to the "Single line layout".
![single-line-layout](https://cloud.githubusercontent.com/assets/207716/24329100/dce73822-1204-11e7-8d90-ddce0d9c28a3.png)

3. Single line layout with day headers turned off.
![single-line-without-day-headers](https://cloud.githubusercontent.com/assets/207716/24329102/e752b368-1204-11e7-9cb3-a535a1bc5bba.png)

4. Single line layout with day headers turned off and "End time" is turned on - end time is shown under start time.
![single-line-no-day-headers-with-end-time](https://cloud.githubusercontent.com/assets/207716/24329106/ef38ccb6-1204-11e7-8071-cb949a1c7306.png)

**Comment by yvolk** [comment]
In order to look "Days from today" column better, I right-aligned numbers in that column:
![screenshot_20170328-072920](https://cloud.githubusercontent.com/assets/207716/24389223/a55aa4e0-1388-11e7-943a-0532f8fed181.png)

**Comment by yvolk** [comment]
To be released in v.1.10.0

**Comment by yvolk** [comment]
The two alternative layouts are now called "Time below title" and "All in one row"
![layout-selection](https://cloud.githubusercontent.com/assets/207716/25063344/a0dbafb6-21ea-11e7-9b68-887f7efd55a3.png)
