### ISSUE TITLE
location not displayed on all day events

### ISSUE THREAD

**Issue by carettasarah** [plusonelabs/calendar-widget#72]
Hi, I love this widget and use it constantly to keep track of my calendar. But I have noticed that if you use the option to display location, it displays onlynfor appointments, but not for all day events. Would be great if you can fix that. Thanks. Sarah.

**Comment by dAF2000** [comment]
These changes in setEventDetails in CalendarEventVisualizer will fix that:

	private void setEventDetails(CalendarEvent event, RemoteViews rv) {
        boolean fillAllDayEvents = prefs.getBoolean(PREF_FILL_ALL_DAY, PREF_FILL_ALL_DAY_DEFAULT);
        boolean showLocation = prefs.getBoolean(PREF_SHOW_LOCATION, PREF_SHOW_LOCATION_DEFAULT);
        boolean timeStringNeeded = !(event.spansOneFullDay() && !(event.isStartOfMultiDayEvent()
            || event.isEndOfMultiDayEvent())
            || event.isAllDay() && fillAllDayEvents);
        boolean locationStringNeeded = showLocation && event.getLocation() != null 
            && !event.getLocation().isEmpty();

        if(!timeStringNeeded && !locationStringNeeded) 
        {
            rv.setViewVisibility(R.id.event_entry_details, View.GONE);
        } 
        else 
        {
            String eventDetails = new String();

            if(timeStringNeeded)
            {
                eventDetails = createTimeSpanString(event);

                if(locationStringNeeded) 
                {
                    eventDetails += SPACE_PIPE_SPACE;
                }
            }

            if(locationStringNeeded) 
            {
                eventDetails += event.getLocation();
            }

            rv.setViewVisibility(R.id.event_entry_details, View.VISIBLE);
            rv.setTextViewText(R.id.event_entry_details, eventDetails);
            setTextSize(context, rv, R.id.event_entry_details, R.dimen.event_entry_details);
            setTextColorFromAttr(context, rv, R.id.event_entry_details, R.attr.eventEntryDetails);
        }
    }

**Comment by yvolk** [comment]
This is fixed in v.3.0, at last. Please check #320
